import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed for Karmix Helper...');

  // 1. Clean existing records (in reverse dependency order)
  await prisma.aIMessage.deleteMany();
  await prisma.aIConversation.deleteMany();
  await prisma.report.deleteMany();
  await prisma.notification.deleteMany();
  await prisma.application.deleteMany();
  await prisma.savedScheme.deleteMany();
  await prisma.requiredDocument.deleteMany();
  await prisma.eligibilityCriteria.deleteMany();
  await prisma.scheme.deleteMany();
  await prisma.governmentSource.deleteMany();
  await prisma.schemeCategory.deleteMany();
  await prisma.userProfile.deleteMany();
  await prisma.user.deleteMany();
  await prisma.searchLog.deleteMany();

  // 2. Create Users (Admin & Citizen)
  const salt = await bcrypt.genSalt(10);
  const adminPasswordHash = await bcrypt.hash('Admin@123456', salt);
  const userPasswordHash = await bcrypt.hash('Citizen@123456', salt);

  const admin = await prisma.user.create({
    data: {
      email: 'admin@karmix.gov.in',
      password: adminPasswordHash,
      name: 'Dr. Sunita Deshmukh',
      phone: '+91 98200 12345',
      role: 'ADMIN',
      preferredLanguage: 'en',
    },
  });

  const citizen = await prisma.user.create({
    data: {
      email: 'citizen@karmix.in',
      password: userPasswordHash,
      name: 'Rahul Anand Patil',
      phone: '+91 94220 98765',
      role: 'CITIZEN',
      preferredLanguage: 'en',
      profile: {
        create: {
          age: 20,
          gender: 'Male',
          state: 'Maharashtra',
          district: 'Pune',
          areaType: 'Urban',
          occupation: 'Student',
          education: 'Undergraduate',
          incomeRange: '1L - 2.5L',
          incomeAmount: 180000,
          casteCategory: 'OBC',
          isMinority: false,
          isDisability: false,
          isBpl: false,
          rationCardType: 'Orange (AAY)',
          maritalStatus: 'Single',
          hasFamilyMembers: 4,
        },
      },
    },
  });

  console.log('✅ Created Admin and Citizen demo accounts.');

  // 3. Create Scheme Categories
  const categoriesData = [
    {
      slug: 'scholarships-education',
      nameEn: 'Education & Scholarships',
      nameMr: 'शिक्षण आणि शिष्यवृत्ती',
      nameHi: 'शिक्षा और छात्रवृत्ति',
      icon: 'GraduationCap',
      descriptionEn: 'Scholarships, fee concessions, stipends, and educational loans for students at all levels.',
      descriptionMr: 'सर्व स्तरांतील विद्यार्थ्यांसाठी शिष्यवृत्ती, फी सवलत, विद्यावेतन आणि शैक्षणिक कर्ज.',
      descriptionHi: 'सभी स्तरों के छात्रों के लिए छात्रवृत्ति, शुल्क छूट, वजीफा और शिक्षा ऋण।',
      displayOrder: 1,
    },
    {
      slug: 'agriculture-farmers',
      nameEn: 'Agriculture & Farmers',
      nameMr: 'कृषी आणि शेतकरी कल्याण',
      nameHi: 'कृषि और किसान कल्याण',
      icon: 'Tractor',
      descriptionEn: 'Crop insurance, input subsidies, irrigation support, and direct income assistance for farmers.',
      descriptionMr: 'शेतकऱ्यांसाठी पीक विमा, खत व बियाणे अनुदान, सिंचन साहाय्य आणि थेट आर्थिक मदत.',
      descriptionHi: 'किसानों के लिए फसल बीमा, इनपुट सब्सिडी, सिंचाई सहायता और प्रत्यक्ष आय सहायता।',
      displayOrder: 2,
    },
    {
      slug: 'healthcare-wellness',
      nameEn: 'Healthcare & Wellness',
      nameMr: 'आरोग्य आणि वैद्यकीय साहाय्य',
      nameHi: 'स्वास्थ्य और कल्याण',
      icon: 'HeartPulse',
      descriptionEn: 'Free hospitalization, health insurance cards, medicines, and maternal care programs.',
      descriptionMr: 'मोफत उपचार, आरोग्य विमा कार्ड, औषधोपचार आणि मातृत्व साहाय्य योजना.',
      descriptionHi: 'मुफ्त अस्पताल में भर्ती, स्वास्थ्य बीमा कार्ड, दवाएं और मातृ देखभाल कार्यक्रम।',
      displayOrder: 3,
    },
    {
      slug: 'business-msme',
      nameEn: 'MSME & Entrepreneurship',
      nameMr: 'उद्योग आणि स्वयंरोजगार',
      nameHi: 'एमएसएमई और उद्यमिता',
      icon: 'Briefcase',
      descriptionEn: 'Collateral-free loans, startup seed funding, equipment subsidies, and business support.',
      descriptionMr: 'विनातारण कर्ज, स्टार्टअप भांडवल, यंत्रसामग्री अनुदान आणि व्यवसाय मार्गदर्शन.',
      descriptionHi: 'संपार्श्विक-मुक्त ऋण, स्टार्टअप सीड फंडिंग, उपकरण सब्सिडी और व्यावसायिक सहायता।',
      displayOrder: 4,
    },
    {
      slug: 'women-child',
      nameEn: 'Women & Child Welfare',
      nameMr: 'महिला आणि बालविकास',
      nameHi: 'महिला एवं बाल विकास',
      icon: 'Users',
      descriptionEn: 'Girl child financial security, maternity benefits, self-help group loans, and nutrition.',
      descriptionMr: 'मुलींचे उज्ज्वल भविष्य, मातृत्व लाभ, बचत गट कर्ज आणि पोषण साहाय्य योजना.',
      descriptionHi: 'बालिका वित्तीय सुरक्षा, मातृत्व लाभ, स्वयं सहायता समूह ऋण और पोषण कार्यक्रम।',
      displayOrder: 5,
    },
    {
      slug: 'housing-shelter',
      nameEn: 'Housing & Shelter',
      nameMr: 'गृहनिर्माण आणि निवारा',
      nameHi: 'आवास और आश्रय',
      icon: 'Home',
      descriptionEn: 'Pucca house construction grants, interest subsidies on home loans, and slum redevelopment.',
      descriptionMr: 'पक्के घर बांधणी अनुदान, गृहकर्जावरील व्याज सवलत आणि गृहनिर्माण योजना.',
      descriptionHi: 'पक्का मकान निर्माण अनुदान, गृह ऋण पर ब्याज सब्सिडी और आवास योजनाएं।',
      displayOrder: 6,
    },
    {
      slug: 'employment-skills',
      nameEn: 'Skill Development & Jobs',
      nameMr: 'कौशल्य विकास आणि रोजगार',
      nameHi: 'कौशल विकास और रोजगार',
      icon: 'Wrench',
      descriptionEn: 'Free technical training, government apprenticeship stipends, and placement programs.',
      descriptionMr: 'मोफत तांत्रिक प्रशिक्षण, शासन विद्यावेतन शिकाऊ उमेदवारी आणि नोकरी मार्गदर्शन.',
      descriptionHi: 'मुफ्त तकनीकी प्रशिक्षण, सरकारी शिक्षुता वजीफा और रोजगार सहायता।',
      displayOrder: 7,
    },
    {
      slug: 'social-security-seniors',
      nameEn: 'Senior Citizens & Pension',
      nameMr: 'ज्येष्ठ नागरिक आणि पेन्शन',
      nameHi: 'वरिष्ठ नागरिक और पेंशन',
      icon: 'ShieldCheck',
      descriptionEn: 'Monthly pensions for elderly, destitute, widows, and social security benefit transfers.',
      descriptionMr: 'ज्येष्ठ, निराधार, विधवा यांच्यासाठी मासिक मानधन आणि सामाजिक सुरक्षा लाभ.',
      descriptionHi: 'बुजुर्गों, निराश्रितों, विधवाओं के लिए मासिक पेंशन और सामाजिक सुरक्षा लाभ।',
      displayOrder: 8,
    },
    {
      slug: 'disability-support',
      nameEn: 'Disability Support (Divyang)',
      nameMr: 'दिव्यांग कल्याण साहाय्य',
      nameHi: 'दिव्यांगजन कल्याण सहायता',
      icon: 'Accessibility',
      descriptionEn: 'Assistive devices, specialized scholarships, self-employment aids, and pension for PwD.',
      descriptionMr: 'साहाय्यक उपकरणे, विशेष शिष्यवृत्ती, स्वयंरोजगार मदत आणि दिव्यांग पेन्शन योजना.',
      descriptionHi: 'सहायक उपकरण, विशेष छात्रवृत्ति, स्व-रोजगार सहायता और दिव्यांग पेंशन।',
      displayOrder: 9,
    },
  ];

  const categories: Record<string, any> = {};
  for (const cat of categoriesData) {
    const created = await prisma.schemeCategory.create({ data: cat });
    categories[cat.slug] = created;
  }
  console.log('✅ Created Scheme Categories.');

  // 4. Create Government Sources
  const sourcesData = [
    {
      name: 'MahaDBT Official Portal',
      domain: 'mahadbt.maharashtra.gov.in',
      officialUrl: 'https://mahadbt.maharashtra.gov.in',
      portalName: 'Direct Benefit Transfer Portal, Government of Maharashtra',
      departmentName: 'Social Justice & Special Assistance Department',
      level: 'STATE',
      state: 'Maharashtra',
      isVerified: true,
    },
    {
      name: 'PM Kisan Samman Nidhi Portal',
      domain: 'pmkisan.gov.in',
      officialUrl: 'https://pmkisan.gov.in',
      portalName: 'PM-Kisan Official Portal',
      departmentName: 'Ministry of Agriculture and Farmers Welfare, Govt of India',
      level: 'CENTRAL',
      state: 'All India',
      isVerified: true,
    },
    {
      name: 'National Health Authority (PM-JAY)',
      domain: 'nha.gov.in',
      officialUrl: 'https://pmjay.gov.in',
      portalName: 'Ayushman Bharat PM-JAY Official Portal',
      departmentName: 'Ministry of Health and Family Welfare, Govt of India',
      level: 'CENTRAL',
      state: 'All India',
      isVerified: true,
    },
    {
      name: 'Pradhan Mantri Awas Yojana - Urban & Gramin',
      domain: 'pmaymis.gov.in',
      officialUrl: 'https://pmaymis.gov.in',
      portalName: 'PMAY Official MIS Portal',
      departmentName: 'Ministry of Housing and Urban Affairs, Govt of India',
      level: 'CENTRAL',
      state: 'All India',
      isVerified: true,
    },
    {
      name: 'Pradhan Mantri Mudra Yojana Portal',
      domain: 'mudra.org.in',
      officialUrl: 'https://www.mudra.org.in',
      portalName: 'MUDRA Official Scheme Portal',
      departmentName: 'Department of Financial Services, Ministry of Finance',
      level: 'CENTRAL',
      state: 'All India',
      isVerified: true,
    },
    {
      name: 'Skill India Digital Hub',
      domain: 'skillindiadigital.gov.in',
      officialUrl: 'https://www.skillindiadigital.gov.in',
      portalName: 'National Apprenticeship Promotion Scheme (NAPS) Portal',
      departmentName: 'Ministry of Skill Development and Entrepreneurship',
      level: 'CENTRAL',
      state: 'All India',
      isVerified: true,
    },
    {
      name: 'PM Vishwakarma Portal',
      domain: 'pmvishwakarma.gov.in',
      officialUrl: 'https://pmvishwakarma.gov.in',
      portalName: 'PM Vishwakarma Official Portal',
      departmentName: 'Ministry of Micro, Small and Medium Enterprises',
      level: 'CENTRAL',
      state: 'All India',
      isVerified: true,
    },
    {
      name: 'National Scholarship Portal (NSP)',
      domain: 'scholarships.gov.in',
      officialUrl: 'https://scholarships.gov.in',
      portalName: 'National Scholarship Portal (NSP 2.0)',
      departmentName: 'Ministry of Electronics & Information Technology / Education',
      level: 'CENTRAL',
      state: 'All India',
      isVerified: true,
    },
    {
      name: 'Maharashtra Social Security Portal',
      domain: 'sjsa.maharashtra.gov.in',
      officialUrl: 'https://sjsa.maharashtra.gov.in',
      portalName: 'Social Justice and Special Assistance Portal, Maharashtra',
      departmentName: 'Social Justice & Special Assistance Department, Govt of Maharashtra',
      level: 'STATE',
      state: 'Maharashtra',
      isVerified: true,
    },
    {
      name: 'Department of Financial Services - SSY',
      domain: 'financialservices.gov.in',
      officialUrl: 'https://financialservices.gov.in',
      portalName: 'National Savings Institute / India Post',
      departmentName: 'Ministry of Finance, Govt of India',
      level: 'CENTRAL',
      state: 'All India',
      isVerified: true,
    },
  ];

  const sources: Record<string, any> = {};
  for (const src of sourcesData) {
    const created = await prisma.governmentSource.create({ data: src });
    sources[src.name] = created;
  }
  console.log('✅ Created Government Sources.');

  // 5. Create Schemes with full details, criteria, and documents
  const schemesData = [
    {
      slug: 'mahadbt-post-matric-scholarship-obc-ebc',
      titleEn: 'MahaDBT Post-Matric Scholarship for OBC & EBC Students',
      titleMr: 'महाडीबीटी मॅट्रिकोत्तर शिष्यवृत्ती योजना (इमाव व इबीसी)',
      titleHi: 'महाडीबीटी पोस्ट-मैट्रिक छात्रवृत्ति (ओबीसी और ईबीसी)',
      shortSummaryEn: '100% tuition and exam fee reimbursement plus maintenance allowance for post-SSC degree/diploma students in Maharashtra.',
      shortSummaryMr: 'महाराष्ट्रातील पदवी व पदविका विद्यार्थ्यांसाठी संपूर्ण शिक्षण शुल्क, परीक्षा फी परतावा आणि निर्वाह भत्ता.',
      shortSummaryHi: 'महाराष्ट्र में उच्च शिक्षा प्राप्त कर रहे ओबीसी और ईबीसी छात्रों के लिए पूर्ण शिक्षण शुल्क प्रतिपूर्ति और निर्वाह भत्ता।',
      detailedDescriptionEn: 'The Government of Maharashtra provides financial assistance to students belonging to Other Backward Classes (OBC) and Economically Backward Classes (EBC) pursuing post-matriculation courses in recognized colleges across Maharashtra. The scheme pays reimbursement directly into student and college bank accounts via DBT.',
      detailedDescriptionMr: 'महाराष्ट्र शासनाच्या इतर मागास बहुजन कल्याण विभागामार्फत राज्यातील मान्यताप्राप्त महाविद्यालयांमध्ये पदविका, पदवी किंवा पदव्युत्तर शिक्षण घेणाऱ्या इतर मागासवर्गीय (OBC) आणि आर्थिकदृष्ट्या मागास (EBC) विद्यार्थ्यांच्या शिक्षणाचा खर्च हलका करण्यासाठी ही शिष्यवृत्ती दिली जाते.',
      detailedDescriptionHi: 'महाराष्ट्र सरकार अन्य पिछड़ा वर्ग (ओबीसी) और आर्थिक रूप से कमजोर वर्ग (ईबीसी) के छात्रों को उच्च शिक्षा जारी रखने के लिए डीबीटी के माध्यम से सीधे शुल्क प्रतिपूर्ति प्रदान करती है।',
      benefitsEn: 'Full Tuition Fee Reimbursement + Exam Fee waiver + Monthly Maintenance Allowance up to ₹1,200/month for hostellers and ₹600/month for day scholars.',
      benefitsMr: 'संपूर्ण शिक्षण शुल्क परतावा + परीक्षा फी सवलत + वसतिगृहातील विद्यार्थ्यांसाठी ₹१,२००/महिना आणि डे-स्कॉलर्ससाठी ₹६००/महिना निर्वाह भत्ता.',
      benefitsHi: 'पूर्ण शिक्षण शुल्क प्रतिपूर्ति + परीक्षा शुल्क माफी + ₹1,200 प्रति माह तक का निर्वाह भत्ता।',
      benefitType: 'Direct Benefit Transfer',
      department: 'Other Backward Bahujan Kalyan Department, Govt of Maharashtra',
      level: 'STATE',
      state: 'Maharashtra',
      categoryId: categories['scholarships-education'].id,
      sourceId: sources['MahaDBT Official Portal'].id,
      applicationMode: 'ONLINE',
      applicationUrl: 'https://mahadbt.maharashtra.gov.in',
      portalName: 'MahaDBT Portal (mahadbt.maharashtra.gov.in)',
      applicationDeadline: '31st March 2026',
      isFeatured: true,
      applicationStepsEn: JSON.stringify([
        'Visit official MahaDBT portal (mahadbt.maharashtra.gov.in) and register using Aadhaar OTP.',
        'Complete Profile section with personal, address, caste, income, and previous qualification details.',
        'Upload scanned documents: Domicile, Income Certificate (Tehsildar), Caste Certificate, and Marksheets.',
        'Navigate to "Other Backward Bahujan Kalyan Dept" schemes and select "Post Matric Scholarship to OBC Students".',
        'Select your current pursuing course, college name, and CAP allotment letter details.',
        'Submit application and save the Application ID for college desk verification and biometric authentication.',
      ]),
      applicationStepsMr: JSON.stringify([
        'अधिकृत महाडीबीटी पोर्टलवर (mahadbt.maharashtra.gov.in) जाऊन आधार ओटीपी द्वारे नोंदणी करा.',
        'वैयक्तिक, पत्ता, जात, उत्पन्न आणि शैक्षणिक माहिती भरून प्रोफाइल पूर्ण करा.',
        'आवश्यक कागदपत्रे (उत्पन्न दाखला, जात प्रमाणपत्र, अधिवास प्रमाणपत्र आणि गुणपत्रिका) अपलोड करा.',
        'इतर मागास बहुजन कल्याण विभाग निवडून "मॅट्रिकोत्तर शिष्यवृत्ती" योजनेवर क्लिक करा.',
        'सध्याचा अभ्यासक्रम, कॉलेजचे नाव व कॅप प्रवेश पत्र निवडा.',
        'अर्ज सबमिट करा व ॲप्लिकेशन आयडी कॉलेज पडताळणीसाठी जतन करा.',
      ]),
      applicationStepsHi: JSON.stringify([
        'आधिकारिक महाडीबीटी पोर्टल (mahadbt.maharashtra.gov.in) पर जाएं और आधार ओटीपी से पंजीकरण करें।',
        'प्रोफाइल सेक्शन में व्यक्तिगत, जाति, आय और शैक्षणिक विवरण भरें।',
        'दस्तावेज अपलोड करें: आय प्रमाण पत्र, जाति प्रमाण पत्र, अधिवास प्रमाण पत्र और अंकतालिका।',
        'योजना का चयन करें और अपने वर्तमान कॉलेज और पाठ्यक्रम का विवरण दर्ज करें।',
        'आवेदन जमा करें और कॉलेज सत्यापन के लिए रसीद सुरक्षित रखें।',
      ]),
      importantNotesEn: 'Ensure your Aadhaar is actively linked to your NPCI bank account for seamless DBT payment.',
      importantNotesMr: 'थेट बँक खात्यात पैसे जमा होण्यासाठी आपले आधार कार्ड बँक खात्याशी NPCI मॅप असणे बंधनकारक आहे.',
      importantNotesHi: 'डीबीटी राशि प्राप्त करने के लिए आपका आधार बैंक खाते (NPCI) से लिंक होना अनिवार्य है।',
      criteria: {
        minAge: 16,
        maxAge: 35,
        allowedGenders: 'Any',
        allowedStates: 'Maharashtra',
        allowedOccupations: JSON.stringify(['Student']),
        allowedEducation: JSON.stringify(['10th Pass', '12th Pass', 'Diploma', 'Undergraduate', 'Post Graduate']),
        maxAnnualIncome: 150000, // Up to 1.5 Lakhs for 100% scholarship, up to 8 Lakhs for Freeship
        allowedCategories: JSON.stringify(['OBC', 'SBC', 'VJNT', 'EWS']),
        requiresDisability: false,
        requiresBpl: false,
        extraConditionsEn: 'Applicant must be a bonafide resident of Maharashtra admitted through CAP / Merit quota.',
        extraConditionsMr: 'अर्जदार महाराष्ट्राचा अधिवासी असावा आणि मान्यताप्राप्त प्रवेश प्रक्रियेतून (CAP) प्रवेश घेतलेला असावा.',
        extraConditionsHi: 'आवेदक महाराष्ट्र का मूल निवासी होना चाहिए और मान्यता प्राप्त कॉलेज में नामांकित होना चाहिए।',
      },
      documents: [
        {
          nameEn: 'Income Certificate (Current Financial Year)',
          nameMr: 'सक्षम अधिकाऱ्याचा चालू वर्षाचा उत्पन्नाचा दाखला (तहसीलदार)',
          nameHi: 'सक्षम प्राधिकारी द्वारा जारी आय प्रमाण पत्र',
          descriptionEn: 'Issued by Tehsildar/Sub-Divisional Officer stating annual family income below ₹1.5 - ₹8 Lakhs.',
          descriptionMr: 'तहसीलदार कार्यालयाकडून वितरित केलेले चालू आर्थिक वर्षाचे उत्पन्नाचे प्रमाणपत्र.',
          isMandatory: true,
          issuanceAuthority: 'Tehsildar / Revenue Department',
          documentType: 'Income',
        },
        {
          nameEn: 'Caste Certificate & Caste Validity',
          nameMr: 'जात प्रमाणपत्र व जात पडताळणी प्रमाणपत्र',
          nameHi: 'जाति प्रमाण पत्र और वैधता',
          descriptionEn: 'Valid Caste Certificate issued by competent authority of Maharashtra.',
          descriptionMr: 'महाराष्ट्र शासनाने दिलेले अधिकृत जात प्रमाणपत्र.',
          isMandatory: true,
          issuanceAuthority: 'Sub-Divisional Magistrate',
          documentType: 'Identity',
        },
        {
          nameEn: 'Maharashtra Domicile Certificate',
          nameMr: 'महाराष्ट्र अधिवास प्रमाणपत्र (Domicile)',
          nameHi: 'महाराष्ट्र निवास प्रमाण पत्र',
          descriptionEn: 'Proof of residence in Maharashtra state.',
          descriptionMr: 'महाराष्ट्र राज्यात वास्तव्याचा दाखला.',
          isMandatory: true,
          issuanceAuthority: 'Tehsildar Office',
          documentType: 'Domicile',
        },
        {
          nameEn: 'Previous Year Marksheet & Fee Receipt',
          nameMr: 'मागील शैक्षणिक वर्षाची गुणपत्रिका व कॉलेज फी पावती',
          nameHi: 'पिछली कक्षा की अंकतालिका और कॉलेज शुल्क रसीद',
          descriptionEn: 'Proof of passing previous qualifying exam and current admission receipt.',
          descriptionMr: 'उत्तीर्ण झाल्याचा पुरावा व सध्याच्या वर्गाची पावती.',
          isMandatory: true,
          issuanceAuthority: 'Educational Institution',
          documentType: 'Education',
        },
        {
          nameEn: 'Aadhaar Card linked with NPCI Bank Account',
          nameMr: 'आधार कार्ड (बँक खात्याशी संलग्न)',
          nameHi: 'आधार कार्ड (बैंक खाते से लिंक)',
          descriptionEn: 'Aadhaar copy and active bank passbook front page.',
          descriptionMr: 'आधार कार्ड व बँकेचे पासबुक प्रत.',
          isMandatory: true,
          issuanceAuthority: 'UIDAI / Nationalized Bank',
          documentType: 'Bank',
        },
      ],
    },
    {
      slug: 'pm-kisan-samman-nidhi',
      titleEn: 'PM Kisan Samman Nidhi Yojana',
      titleMr: 'प्रधानमंत्री किसान सन्मान निधी योजना',
      titleHi: 'प्रधानमंत्री किसान सम्मान निधि योजना',
      shortSummaryEn: 'Direct income support of ₹6,000 per year in three equal installments of ₹2,000 to all landholding farmer families.',
      shortSummaryMr: 'शेतकरी कुटुंबांना दरवर्षी ₹६,००० ची थेट आर्थिक मदत (दर ४ महिन्यांनी ₹२,००० चे तीन समान हप्ते).',
      shortSummaryHi: 'सभी पात्र किसान परिवारों को प्रति वर्ष ₹6,000 की प्रत्यक्ष आय सहायता (तीन समान किस्तों में ₹2,000)।',
      detailedDescriptionEn: 'PM-KISAN is a Central Sector scheme with 100% funding from Government of India. Under the scheme, income support of ₹6,000/- per year in three equal installments is provided to all landholding farmer families, subject to certain exclusion criteria relating to higher income brackets.',
      detailedDescriptionMr: 'प्रधानमंत्री किसान सन्मान निधी ही केंद्र शासनाची महत्त्वाकांक्षी योजना असून याद्वारे शेतकरी कुटुंबांना शेती निविष्ठा, बियाणे, खते खरेदी करण्यासाठी वार्षिक ₹६,००० थेट बँक खात्यात पाठवले जातात.',
      detailedDescriptionHi: 'प्रधानमंत्री किसान सम्मान निधि भारत सरकार की 100% वित्त पोषित योजना है। इसके तहत किसानों को कृषि और घरेलू जरूरतों के लिए प्रति वर्ष ₹6,000 तीन किस्तों में दिए जाते हैं।',
      benefitsEn: '₹6,000 annually credited directly to Aadhaar-seeded bank accounts via DBT in 3 installments (April-July, August-November, December-March).',
      benefitsMr: 'वार्षिक ₹६,००० थेट बँक खात्यात जमा (दर चार महिन्यांनी ₹२,००० चे तीन हप्ते).',
      benefitsHi: '₹6,000 प्रति वर्ष डीबीटी के माध्यम से सीधे बैंक खाते में हस्तांतरित।',
      benefitType: 'Direct Benefit Transfer',
      department: 'Department of Agriculture & Farmers Welfare, Ministry of Agriculture',
      level: 'CENTRAL',
      state: 'All India',
      categoryId: categories['agriculture-farmers'].id,
      sourceId: sources['PM Kisan Samman Nidhi Portal'].id,
      applicationMode: 'ONLINE',
      applicationUrl: 'https://pmkisan.gov.in',
      portalName: 'PM-Kisan Portal (pmkisan.gov.in)',
      applicationDeadline: 'Rolling / Always Open',
      isFeatured: true,
      applicationStepsEn: JSON.stringify([
        'Visit the official PM-Kisan portal (pmkisan.gov.in) and click "New Farmer Registration".',
        'Enter your Aadhaar number, Mobile number, and select your State/District.',
        'Authenticate using the Aadhaar OTP received on registered mobile.',
        'Enter land details: Khata/Khatauni number, Survey number, and Area in Hectares from 7/12 (Satbara) extract.',
        'Upload land holding record and submit the application for Patwari and District Revenue verification.',
        'Complete Mandatory e-KYC via Face Authentication or Biometric CSC center.',
      ]),
      applicationStepsMr: JSON.stringify([
        'अधिकृत pmkisan.gov.in पोर्टलवर जाऊन "New Farmer Registration" वर क्लिक करा.',
        'आधार क्रमांक आणि मोबाईल क्रमांक नोंदवून ओटीपी पडताळणी करा.',
        'जमिनीचा तपशील (खाते क्रमांक, गट क्रमांक आणि क्षेत्रफळ ७/१२ प्रमाणे) नोंदवा.',
        'जमिनीचा ७/१२ व ८-अ उतारा अपलोड करून अर्ज सबमिट करा.',
        'तलाठी आणि तालुका कृषी अधिकाऱ्यांच्या मंजुरीनंतर हप्ता सुरू होतो.',
        'मोबाईल ॲपद्वारे फेस ऑथेंटिकेशन किंवा सीएससी सेंटरवर जाऊन अनिवार्य e-KYC पूर्ण करा.',
      ]),
      applicationStepsHi: JSON.stringify([
        'pmkisan.gov.in पर जाएं और "New Farmer Registration" चुनें।',
        'आधार नंबर और मोबाइल नंबर दर्ज करके ओटीपी से सत्यापित करें।',
        'जमीन का खसरा/खतौनी विवरण दर्ज करें।',
        'भू-अभिलेख अपलोड करें और आवेदन जमा करें।',
        'पीएम-किसान पोर्टल या सीएससी केंद्र पर अनिवार्य ई-केवाईसी पूरा करें।',
      ]),
      importantNotesEn: 'Mandatory e-KYC and Aadhaar-Bank account seeding are required to receive the quarterly installments.',
      importantNotesMr: 'हप्ता मिळण्यासाठी ई-केवायसी (e-KYC) आणि आधार-बँक लिंकिंग पूर्ण असणे अत्यंत आवश्यक आहे.',
      importantNotesHi: 'किस्त प्राप्त करने के लिए ई-केवाईसी और बैंक खाते से आधार लिंक होना आवश्यक है।',
      criteria: {
        minAge: 18,
        maxAge: 100,
        allowedGenders: 'Any',
        allowedStates: 'All India',
        allowedOccupations: JSON.stringify(['Farmer']),
        allowedEducation: 'Any',
        maxAnnualIncome: 800000,
        allowedCategories: 'Any',
        requiresDisability: false,
        requiresBpl: false,
        extraConditionsEn: 'Must own cultivable agricultural land in name. Institutional landholders and income tax payers are excluded.',
        extraConditionsMr: 'स्वतःच्या नावावर लागवडीयोग्य शेतजमीन असणे आवश्यक. प्राप्तिकर (Income Tax) भरणारे शेतकरी अपात्र ठरतात.',
        extraConditionsHi: 'स्वयं के नाम पर कृषि भूमि होनी चाहिए। आयकर दाता इस योजना के पात्र नहीं हैं।',
      },
      documents: [
        {
          nameEn: '7/12 (Satbara) & 8-A Land Record Extract',
          nameMr: 'जमिनीचा चालू ७/१२ आणि ८-अ उतारा (Digitally Signed)',
          nameHi: 'जमीन का खतौनी/भू-अभिलेख रिकॉर्ड',
          descriptionEn: 'Current land ownership document reflecting applicant name.',
          descriptionMr: 'स्वतःच्या मालकीचा जमिनीचा अधिकृत उतारा.',
          isMandatory: true,
          issuanceAuthority: 'Revenue Department / Mahabhulekh',
          documentType: 'Land',
        },
        {
          nameEn: 'Aadhaar Card',
          nameMr: 'आधार कार्ड',
          nameHi: 'आधार कार्ड',
          descriptionEn: 'Aadhaar of applicant linked to active mobile.',
          descriptionMr: 'मोबाईल संलग्न आधार कार्ड प्रत.',
          isMandatory: true,
          issuanceAuthority: 'UIDAI',
          documentType: 'Identity',
        },
        {
          nameEn: 'Bank Account Passbook (Aadhaar Seeded)',
          nameMr: 'आधार संलग्न बँक पासबुक',
          nameHi: 'बैंक पासबुक',
          descriptionEn: 'Bank passbook showing IFSC code and active account status.',
          descriptionMr: 'बँक खाते क्रमांक व आयएफएससी कोड दर्शवणारे पासबुक.',
          isMandatory: true,
          issuanceAuthority: 'Bank',
          documentType: 'Bank',
        },
      ],
    },
    {
      slug: 'ayushman-bharat-pm-jay-health-card',
      titleEn: 'Ayushman Bharat PM-JAY (Golden Health Card)',
      titleMr: 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (आरोग्य कार्ड)',
      titleHi: 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (गोल्डन कार्ड)',
      shortSummaryEn: 'Cashless health insurance coverage up to ₹5,00,000 per family per year for secondary and tertiary hospitalization across 28,000+ empaneled hospitals.',
      shortSummaryMr: 'कुटुंबासाठी दरवर्षी ₹५,००,००० पर्यंत मोफत आणि कॅशलेस उपचार (२८,००० हून अधिक सरकारी व खाजगी रुग्णालयांमध्ये).',
      shortSummaryHi: 'प्रति परिवार प्रति वर्ष ₹5,00,000 तक का मुफ्त कैशलेस स्वास्थ्य बीमा 28,000 से अधिक सूचीबद्ध अस्पतालों में।',
      detailedDescriptionEn: 'Ayushman Bharat PM-JAY is the world’s largest government-funded health assurance scheme. It provides a cover of ₹5 Lakh per family per year for secondary and tertiary care hospitalization to over 12 crore poor and vulnerable families (approx 55 crore beneficiaries).',
      detailedDescriptionMr: 'आयुष्मान भारत - महात्मा ज्योतिराव फुले जन आरोग्य योजना संयुक्त अभियानांतर्गत पात्र नागरिकांना गंभीर आजारांवर ₹५ लाखांपर्यंत मोफत उपचार मिळतात. यामध्ये औषधोपचार, शस्त्रक्रिया, तपासण्या आणि रुग्णालयात भरतीचा खर्च समाविष्ट आहे.',
      detailedDescriptionHi: 'आयुष्मान भारत योजना के तहत देश के 55 करोड़ से अधिक नागरिकों को अस्पताल में भर्ती होने पर 5 लाख रुपये तक का कैशलेस इलाज मुफ्त मिलता है।',
      benefitsEn: 'Cashless hospital treatment up to ₹5 Lakhs/year including surgeries, intensive care, diagnostics, medicines, and pre/post hospitalization expenses.',
      benefitsMr: 'वार्षिक ₹५ लाख रुपयांपर्यंत मोफत उपचार, शस्त्रक्रिया, औषधे, तपासण्या आणि कॅशलेस सुविधा.',
      benefitsHi: 'प्रति वर्ष ₹5 लाख तक का कैशलेस अस्पताल उपचार, सर्जरी और दवाएं।',
      benefitType: 'Health Insurance',
      department: 'National Health Authority, Ministry of Health and Family Welfare',
      level: 'CENTRAL',
      state: 'All India',
      categoryId: categories['healthcare-wellness'].id,
      sourceId: sources['National Health Authority (PM-JAY)'].id,
      applicationMode: 'BOTH',
      applicationUrl: 'https://beneficiary.nha.gov.in',
      portalName: 'Ayushman Beneficiary Portal (beneficiary.nha.gov.in)',
      applicationDeadline: 'Rolling / Always Open',
      isFeatured: true,
      applicationStepsEn: JSON.stringify([
        'Visit official portal beneficiary.nha.gov.in or download the Ayushman App.',
        'Enter mobile number, select state and search by Aadhaar Number, Ration Card, or PM-JAY ID.',
        'Check if family members are listed in the eligible SECC / NFSA database.',
        'Click "e-KYC", authenticate using Aadhaar OTP / IRIS / Face Match.',
        'Upon instant approval, download the official Ayushman Bharat PVC Card.',
        'Show this card at any empaneled government or private hospital Ayushman Mitra desk for cashless admission.',
      ]),
      applicationStepsMr: JSON.stringify([
        'beneficiary.nha.gov.in या संकेतस्थळाला भेट द्या किंवा आयुष्मान ॲप डाउनलोड करा.',
        'मोबाईल नंबर आणि आधार क्रमांक / शिधापत्रिका क्रमांक टाकून पात्रता शोधा.',
        'कुटुंबातील सदस्यांची नावे तपासा आणि ई-केवायसी (e-KYC) पूर्ण करा.',
        'आधार ओटीपी किंवा फेस ऑथेंटिकेशन द्वारे तत्काळ मंजुरी मिळवा.',
        'अधिकृत आयुष्मान गोल्डन कार्ड डाऊनलोड करा.',
        'कोणत्याही अधिकृत रुग्णालयात जाऊन आयुष्मान मित्राकडे कार्ड दाखवून मोफत उपचार घ्या.',
      ]),
      applicationStepsHi: JSON.stringify([
        'beneficiary.nha.gov.in पर जाएं या आयुष्मान ऐप का उपयोग करें।',
        'आधार या राशन कार्ड नंबर दर्ज करके परिवार की पात्रता जांचें।',
        'आधार ओटीपी या फेस स्कैन से ई-केवाईसी पूरी करें।',
        'स्वीकृति के बाद तुरंत आयुष्मान कार्ड डाउनलोड करें।',
        'सूचीबद्ध अस्पताल में आयुष्मान मित्र को कार्ड दिखाकर कैशलेस उपचार प्राप्त करें।',
      ]),
      importantNotesEn: 'No family size limit and no age cap. All pre-existing conditions are covered from day one.',
      importantNotesMr: 'कुटुंबाच्या आकाराची किंवा वयाची कोणतीही मर्यादा नाही. जुने आजार पहिल्या दिवसापासून कव्हर केले जातात.',
      importantNotesHi: 'परिवार के सदस्यों की कोई सीमा नहीं है। पहले से मौजूद सभी बीमारियां पहले दिन से कवर होती हैं।',
      criteria: {
        minAge: 0,
        maxAge: 100,
        allowedGenders: 'Any',
        allowedStates: 'All India',
        allowedOccupations: 'Any',
        allowedEducation: 'Any',
        maxAnnualIncome: 300000,
        allowedCategories: 'Any',
        requiresDisability: false,
        requiresBpl: false,
        extraConditionsEn: 'Available to families registered in SECC 2011 database or possessing NFSA / BPL / AAY Ration Cards (Yellow/Orange in Maharashtra).',
        extraConditionsMr: 'पिवळे किंवा केशरी रेशनकार्ड धारक किंवा SECC यादीतील पात्र कुटुंबे पात्र आहेत.',
        extraConditionsHi: 'राशन कार्ड धारक या SECC डेटाबेस में शामिल परिवार इसके पात्र हैं।',
      },
      documents: [
        {
          nameEn: 'Aadhaar Card',
          nameMr: 'आधार कार्ड',
          nameHi: 'आधार कार्ड',
          descriptionEn: 'Aadhaar of all family members to be linked.',
          descriptionMr: 'कुटुंबातील सर्व सदस्यांचे आधार कार्ड.',
          isMandatory: true,
          issuanceAuthority: 'UIDAI',
          documentType: 'Identity',
        },
        {
          nameEn: 'Ration Card (NFSA / State Public Distribution)',
          nameMr: 'रेशन कार्ड (शिधापत्रिका)',
          nameHi: 'राशन कार्ड',
          descriptionEn: 'Yellow / Orange Ration card stating family composition.',
          descriptionMr: 'कुटुंब सदस्यांची नावे असलेले वैध रेशन कार्ड.',
          isMandatory: true,
          issuanceAuthority: 'Food & Civil Supplies Department',
          documentType: 'Identity',
        },
      ],
    },
    {
      slug: 'pradhan-mantri-mudra-yojana-pmmy',
      titleEn: 'Pradhan Mantri MUDRA Yojana (PMMY)',
      titleMr: 'प्रधानमंत्री मुद्रा योजना (PMMY स्वयंरोजगार कर्ज)',
      titleHi: 'प्रधानमंत्री मुद्रा योजना (पीएमएमवाई)',
      shortSummaryEn: 'Collateral-free business loans up to ₹20,00,000 for micro and small enterprises, shopkeepers, artisans, and new startups under Shishu, Kishore, and Tarun categories.',
      shortSummaryMr: 'लघु व सूक्ष्म उद्योजक, व्यावसायिक, दुकानदार यांच्यासाठी विनातारण ₹२० लाखांपर्यंत व्यवसाय कर्ज.',
      shortSummaryHi: 'सूक्ष्म और लघु उद्यमों के लिए ₹20 लाख तक का संपार्श्विक-मुक्त व्यावसायिक ऋण।',
      detailedDescriptionEn: 'PMMY enables micro and small non-corporate, non-farm enterprises to access collateral-free institutional credit. Categories include Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 Lakhs), and Tarun / Tarun Plus (₹5 Lakhs to ₹20 Lakhs) with subsidized interest rates.',
      detailedDescriptionMr: 'सूक्ष्म, लघु व मध्यम उद्योग सुरू करण्यासाठी किंवा वाढवण्यासाठी बँकांमार्फत विनातारण सुलभ कर्ज पुरवठा केला जातो. यामध्ये शिशु (₹५० हजारांपर्यंत), किशोर (₹५ लाखांपर्यंत) आणि तरुण (₹२० लाखांपर्यंत) असे तीन टप्पे आहेत.',
      detailedDescriptionHi: 'पीएमएमवाई गैर-कॉर्पोरेट, गैर-कृषि लघु/सूक्ष्म उद्यमों को आय सृजन गतिविधियों के लिए 20 लाख रुपये तक का संपार्श्विक-मुक्त ऋण प्रदान करता है।',
      benefitsEn: 'No collateral/guarantee required, affordable interest rates (8.5% - 11%), MUDRA Debit Card for working capital, flexible repayment period up to 5-7 years.',
      benefitsMr: 'कोणतेही तारण न लागणारे कर्ज, वाजवी व्याजदर, खेळत्या भांडवलासाठी मुद्रा डेबिट कार्ड आणि परतफेडीसाठी ५ ते ७ वर्षांची सुलभ मुदत.',
      benefitsHi: 'बिना किसी गारंटी के ऋण, किफायती ब्याज दरें, कार्यशील पूंजी के लिए मुद्रा डेबिट कार्ड।',
      benefitType: 'Loan',
      department: 'Department of Financial Services, Ministry of Finance',
      level: 'CENTRAL',
      state: 'All India',
      categoryId: categories['business-msme'].id,
      sourceId: sources['Pradhan Mantri Mudra Yojana Portal'].id,
      applicationMode: 'BOTH',
      applicationUrl: 'https://www.udyamimitra.in',
      portalName: 'Udyami Mitra / JanSamarth Portal',
      applicationDeadline: 'Rolling / Always Open',
      isFeatured: true,
      applicationStepsEn: JSON.stringify([
        'Prepare a brief Business Plan / Project Report outlining estimated revenue, machinery cost, and working capital needs.',
        'Visit Udyami Mitra portal (udyamimitra.in) or JanSamarth portal (jansamarth.in).',
        'Choose loan category: Shishu (up to ₹50k), Kishore (₹50k-5L), or Tarun (₹5L-20L).',
        'Fill applicant KYC, business registration/Udyam certificate, and upload quotations for machinery/inventory.',
        'Select preferred commercial or cooperative bank branch in your locality.',
        'Bank branch verifies documents and sanctions the loan directly without asking for third-party collateral.',
      ]),
      applicationStepsMr: JSON.stringify([
        'आपल्या व्यवसायाचा संक्षिप्त प्रकल्प आराखडा (Project Report) आणि खर्चाचा अंदाज तयार करा.',
        'udyamimitra.in किंवा jansamarth.in पोर्टलवर ऑनलाइन अर्ज भरा.',
        'कर्जाचा टप्पा निवडा: शिशु (₹५० हजार), किशोर (₹५० हजार - ५ लाख), किंवा तरुण (₹५ लाख - २० लाख).',
        'केवायसी, उद्योग आधार (Udyam) आणि साहित्याचे कोटेशन अपलोड करा.',
        'नजीकच्या राष्ट्रीयीकृत किंवा सहकारी बँकेची शाखा निवडा.',
        'बँक पडताळणीनंतर विनातारण कर्ज मंजूर करते.',
      ]),
      applicationStepsHi: JSON.stringify([
        'व्यावसायिक परियोजना रिपोर्ट और आवश्यक मशीनरी का कोटेशन तैयार करें।',
        'जनसमर्थ पोर्टल (jansamarth.in) या नजदीकी बैंक शाखा में आवेदन करें।',
        'ऋण श्रेणी (शिशु, किशोर, तरुण) का चयन करें।',
        'केवाईसी, पैन, आधार और उद्यम पंजीकरण दस्तावेज संलग्न करें।',
        'सत्यापन के पश्चात बैंक द्वारा ऋण राशि सीधे स्वीकृत की जाती है।',
      ]),
      importantNotesEn: 'Banks are strictly mandated not to demand collateral security for loans sanctioned under MUDRA up to ₹10 Lakhs.',
      importantNotesMr: 'मुद्रा योजनेअंतर्गत ₹१० लाखांपर्यंतच्या कर्जासाठी बँकांनी तारण (Security) मागण्यास सक्त मनाई आहे.',
      importantNotesHi: 'मुद्रा ऋण के लिए बैंकों द्वारा संपार्श्विक सुरक्षा (Collateral) की मांग नहीं की जा सकती।',
      criteria: {
        minAge: 18,
        maxAge: 65,
        allowedGenders: 'Any',
        allowedStates: 'All India',
        allowedOccupations: JSON.stringify(['Business Owner', 'Unemployed', 'Daily Wage', 'Farmer', 'Other']),
        allowedEducation: 'Any',
        maxAnnualIncome: null,
        allowedCategories: 'Any',
        requiresDisability: false,
        requiresBpl: false,
        extraConditionsEn: 'Applicant must not be a defaulter to any bank or financial institution.',
        extraConditionsMr: 'अर्जदार कोणत्याही बँकेचा थकीत कर्जदार (Defaulter) नसावा.',
        extraConditionsHi: 'आवेदक किसी भी बैंक का डिफ़ॉल्टर नहीं होना चाहिए।',
      },
      documents: [
        {
          nameEn: 'Identity Proof (Aadhaar / PAN / Voter ID)',
          nameMr: 'ओळख पुरावा (आधार / पॅन / मतदार ओळखपत्र)',
          nameHi: 'पहचान प्रमाण (आधार/पैन)',
          descriptionEn: 'Government photo identity card.',
          descriptionMr: 'शासकीय फोटो ओळखपत्र.',
          isMandatory: true,
          issuanceAuthority: 'Govt of India',
          documentType: 'Identity',
        },
        {
          nameEn: 'Business Address Proof & Udyam Registration',
          nameMr: 'व्यवसाय नोंदणी प्रमाणपत्र (Udyam Registration / Shop Act)',
          nameHi: 'उद्यम पंजीकरण प्रमाण पत्र / दुकान अधिनियम',
          descriptionEn: 'Proof of business operation or municipal shop act license.',
          descriptionMr: 'उद्योग आधार किंवा शॉप ॲक्ट लायसन्स.',
          isMandatory: false,
          issuanceAuthority: 'Ministry of MSME / Municipal Corp',
          documentType: 'Other',
        },
        {
          nameEn: 'Quotation of Machinery / Items to be Purchased',
          nameMr: 'खरेदी करावयाच्या यंत्रसामग्रीचे अधिकृत कोटेशन',
          nameHi: 'उपकरणों/सामग्रियों का कोटेशन',
          descriptionEn: 'Proforma invoice from authorized vendor for capital expenditure.',
          descriptionMr: 'अधिकृत विक्रेत्याचे दरपत्रक.',
          isMandatory: true,
          issuanceAuthority: 'Authorized Vendor',
          documentType: 'Other',
        },
        {
          nameEn: 'Last 6 Months Bank Statement',
          nameMr: 'मागील ६ महिन्यांचे बँक स्टेटमेंट',
          nameHi: 'पिछले 6 महीनों का बैंक विवरण',
          descriptionEn: 'Bank statement of savings or current account.',
          descriptionMr: 'चालू किंवा बचत खात्याचा बँक हिशोब.',
          isMandatory: true,
          issuanceAuthority: 'Bank',
          documentType: 'Bank',
        },
      ],
    },
    {
      slug: 'pm-vishwakarma-scheme',
      titleEn: 'PM Vishwakarma Kaushal Samman Yojana',
      titleMr: 'प्रधानमंत्री विश्वकर्मा कौशल्य सन्मान योजना',
      titleHi: 'प्रधानमंत्री विश्वकर्मा योजना',
      shortSummaryEn: 'End-to-end holistic support for traditional artisans and craftspeople: ₹15,000 tool kit grant, 5-7 days paid skill training (₹500/day), and collateral-free credit up to ₹3,00,000 at 5% interest.',
      shortSummaryMr: 'पारंपरिक १८ कारागिरांसाठी ₹१५,००० मोफत टूलकिट अनुदान, दररोज ₹५०० मानधनासह आधुनिक प्रशिक्षण आणि ५% व्याजाने ₹३ लाखांपर्यंत सुलभ कर्ज.',
      shortSummaryHi: 'पारंपरिक 18 ट्रेड के कारीगरों के लिए ₹15,000 टूलकिट अनुदान, ₹500/दिन वजीफे के साथ कौशल प्रशिक्षण और 5% ब्याज पर ₹3 लाख तक का ऋण।',
      detailedDescriptionEn: 'PM Vishwakarma provides end-to-end support to traditional artisans and craftspeople engaged in 18 trades (carpenter, blacksmith, goldsmith, potter, cobbler, tailor, mason, etc.). Offers digital identity, free skill upgrade, tool-kit incentive of ₹15,000, credit support up to ₹3 Lakhs in 2 tranches, and marketing linkages.',
      detailedDescriptionMr: 'सुतार, लोहार, कुंभार, सोनार, चर्मकार, गवंडी, शिंपी अशा १८ पारंपरिक व्यवसायातील कारागिरांना आर्थिक व तांत्रिक बळ देण्यासाठी केंद्र शासनाची ही सर्वसमावेशक योजना आहे.',
      detailedDescriptionHi: 'पारंपरिक कारीगरों और शिल्पकारों को अपनी कला और आजीविका को सशक्त बनाने के लिए टूलकिट, आधुनिक प्रशिक्षण और न्यूनतम ब्याज पर वित्तीय सहायता दी जाती है।',
      benefitsEn: 'PM Vishwakarma Certificate & ID Card + Free Basic (5-7 days) & Advanced (15 days) training with ₹500/day stipend + ₹15,000 e-Voucher for toolkits + ₹3 Lakh enterprise loan at only 5% interest.',
      benefitsMr: 'अधिकृत प्रमाणपत्र व ओळखपत्र + दररोज ₹५०० विद्यावेतनासह मोफत प्रशिक्षण + ₹१५,००० टूलकिट व्हाऊचर + ५% सवलतीच्या व्याजाने ₹३ लाखांपर्यंत कर्ज.',
      benefitsHi: 'विश्वकर्मा प्रमाण पत्र + ₹500/दिन वजीफा + ₹15,000 टूलकिट वाउचर + 5% रियायती ब्याज पर ₹3 लाख तक का ऋण।',
      benefitType: 'Training & Subsidy',
      department: 'Ministry of Micro, Small & Medium Enterprises, Govt of India',
      level: 'CENTRAL',
      state: 'All India',
      categoryId: categories['employment-skills'].id,
      sourceId: sources['PM Vishwakarma Portal'].id,
      applicationMode: 'BOTH',
      applicationUrl: 'https://pmvishwakarma.gov.in',
      portalName: 'PM Vishwakarma Portal (pmvishwakarma.gov.in)',
      applicationDeadline: 'Rolling / Always Open',
      isFeatured: true,
      applicationStepsEn: JSON.stringify([
        'Visit your nearest Common Service Centre (CSC) with Aadhaar, linked mobile, and bank passbook.',
        'CSC operator performs biometric verification and registers on pmvishwakarma.gov.in.',
        'Select your traditional trade from the 18 eligible trades (e.g. Carpenter, Blacksmith, Tailor, Mason).',
        'Application undergoes 3-tier verification: Gram Panchayat / Urban Local Body, District Implementation Committee, and Screening Committee.',
        'Upon approval, receive PM Vishwakarma Digital ID & enroll in 5-day basic training at nearby training center.',
        'Receive ₹15,000 toolkit digital voucher on completion of training.',
      ]),
      applicationStepsMr: JSON.stringify([
        'नजीकच्या ' + 'आपले सरकार' + ' किंवा सीएससी (CSC) केंद्रावर आधार व बँक पासबुकसह जा.',
        'बायोमेट्रिक पडताळणी करून १८ पारंपरिक व्यवसायांपैकी आपला व्यवसाय निवडा.',
        'ग्रामपंचायत/नगरपालिका व जिल्हा समितीद्वारे अर्जाची पडताळणी केली जाते.',
        'मंजुरीनंतर ५ दिवसांचे मूलभूत प्रशिक्षण पूर्ण करा, ज्यामध्ये दररोज ₹५०० मिळतील.',
        'प्रशिक्षण पूर्ण होताच साधनांसाठी ₹१५,००० चे डिजिटल व्हाऊचर प्राप्त करा.',
      ]),
      applicationStepsHi: JSON.stringify([
        'निकटतम सीएससी (CSC) केंद्र पर जाएं और आधार बायोमेट्रिक सत्यापन कराएं।',
        '18 पारंपरिक शिल्पों में से अपना ट्रेड चुनें।',
        'ग्राम पंचायत और जिला समिति द्वारा सत्यापन किया जाता है।',
        'स्वीकृति के बाद 5-7 दिवसीय प्रशिक्षण में भाग लें (प्रति दिन ₹500 वजीफा)।',
        'प्रशिक्षण के बाद ₹15,000 का टूलकिट वाउचर प्राप्त करें।',
      ]),
      importantNotesEn: 'One family member per household is eligible. Self-declaration of traditional artisan trade verified by Gram Pradhan / Ward Member.',
      importantNotesMr: 'एका कुटुंबातील एकाच सदस्याला लाभ मिळतो. स्थानिक ग्रामसेवक किंवा नगरसेवकाची शिफारस आवश्यक असते.',
      importantNotesHi: 'एक परिवार से एक ही सदस्य पात्र है। पारंपरिक कारीगरी का स्व-घोषणा पत्र आवश्यक है।',
      criteria: {
        minAge: 18,
        maxAge: 70,
        allowedGenders: 'Any',
        allowedStates: 'All India',
        allowedOccupations: JSON.stringify(['Daily Wage', 'Business Owner', 'Unemployed', 'Other']),
        allowedEducation: 'Any',
        maxAnnualIncome: null,
        allowedCategories: 'Any',
        requiresDisability: false,
        requiresBpl: false,
        extraConditionsEn: 'Must be actively practicing one of the 18 specified traditional craft trades with hands/tools.',
        extraConditionsMr: '१८ निर्देशित पारंपरिक कारागीर व्यवसायांपैकी एक व्यवसाय सक्रियपणे करत असावा.',
        extraConditionsHi: 'निर्दिष्ट 18 पारंपरिक शिल्पों में से किसी एक में कार्यरत होना चाहिए।',
      },
      documents: [
        {
          nameEn: 'Aadhaar Card (Biometric Verification)',
          nameMr: 'आधार कार्ड (बायोमेट्रिक पडताळणीसाठी)',
          nameHi: 'आधार कार्ड',
          descriptionEn: 'Aadhaar card with active mobile number linkage.',
          descriptionMr: 'सक्रिय मोबाईलशी संलग्न आधार.',
          isMandatory: true,
          issuanceAuthority: 'UIDAI',
          documentType: 'Identity',
        },
        {
          nameEn: 'Bank Passbook Copy',
          nameMr: 'बँक खाते पासबुक',
          nameHi: 'बैंक पासबुक',
          descriptionEn: 'Passbook with clear account number and IFSC.',
          descriptionMr: 'बँक खात्याची प्रत.',
          isMandatory: true,
          issuanceAuthority: 'Bank',
          documentType: 'Bank',
        },
        {
          nameEn: 'Self-Declaration of Trade & Skill Practice',
          nameMr: 'पारंपरिक व्यवसाय स्व-घोषणापत्र',
          nameHi: 'व्यावसायिक स्व-घोषणा पत्र',
          descriptionEn: 'Form filled at CSC regarding years in trade.',
          descriptionMr: 'व्यवसायातील अनुभवाचे स्वयंघोषणापत्र.',
          isMandatory: true,
          issuanceAuthority: 'Self / CSC',
          documentType: 'Other',
        },
      ],
    },
    {
      slug: 'sukanya-samriddhi-yojana-ssy',
      titleEn: 'Sukanya Samriddhi Yojana (SSY)',
      titleMr: 'सुकन्या समृद्धी योजना (मुलींच्या उज्ज्वल भविष्यासाठी)',
      titleHi: 'सुकन्या समृद्धि योजना (एसएसवाई)',
      shortSummaryEn: 'High-interest government savings scheme (8.2% p.a.) with 100% tax exemption under Section 80C to secure girl child higher education and marriage.',
      shortSummaryMr: 'मुलींच्या उच्च शिक्षण व विवाहासाठी केंद्र शासनाची सर्वोच्च व्याजदर देणारी (८.२% वार्षिक) व करमुक्त बचत योजना.',
      shortSummaryHi: 'बेटियों की उच्च शिक्षा और विवाह के लिए सरकार समर्थित उच्च ब्याज दर (8.2% प्रति वर्ष) और धारा 80C के तहत पूर्ण कर छूट वाली बचत योजना।',
      detailedDescriptionEn: 'Sukanya Samriddhi Account is a Government of India backed savings scheme targeted at the parents of girl children. The scheme encourages parents to build a fund for the future education and marriage expenses of their female child. It offers one of the highest sovereign-guaranteed interest rates in India.',
      detailedDescriptionMr: 'बेटी बचाओ, बेटी पढाओ अभियानांतर्गत १० वर्षांखालील मुलींच्या नावाने पोस्ट ऑफिस किंवा राष्ट्रीयीकृत बँकेत हे खाते उघडता येते. यामध्ये वार्षिक किमान ₹२५० ते कमाल ₹१.५ लाखांपर्यंत गुंतवणूक करता येते.',
      detailedDescriptionHi: 'सुकन्या समृद्धि खाता 10 वर्ष से कम आयु की बालिकाओं के लिए खोला जा सकता है। यह योजना सरकार द्वारा 8.2% की आकर्षक ब्याज दर और पूर्ण आयकर छूट प्रदान करती है।',
      benefitsEn: 'Attractive 8.2% compounded annual interest rate + Complete Triple Tax Exemption (EEE on deposit, interest, and maturity) under Sec 80C.',
      benefitsMr: '८.२% चक्रवाढ वार्षिक व्याजदर + कलम ८०सी अंतर्गत संपूर्ण कर सवलत + १८ व्या वर्षानंतर ५०% उच्च शिक्षणासाठी काढण्याची मुभा.',
      benefitsHi: '8.2% चक्रवृद्धि ब्याज दर + धारा 80सी के तहत पूर्ण कर छूट (EEE)।',
      benefitType: 'Subsidy & Savings',
      department: 'Department of Economic Affairs, Ministry of Finance',
      level: 'CENTRAL',
      state: 'All India',
      categoryId: categories['women-child'].id,
      sourceId: sources['Department of Financial Services - SSY'].id,
      applicationMode: 'BOTH',
      applicationUrl: 'https://www.indiapost.gov.in',
      portalName: 'India Post / Authorized Commercial Banks',
      applicationDeadline: 'Rolling / Open until girl turns 10',
      isFeatured: false,
      applicationStepsEn: JSON.stringify([
        'Collect SSY Account Opening Form from any India Post Office branch or designated public/private sector bank.',
        'Fill girl child details, guardian KYC, and initial deposit amount (minimum ₹250).',
        'Attach child Birth Certificate and parent/guardian Aadhaar and PAN cards.',
        'Submit the form with cash/cheque at the counter.',
        'Receive the SSY Passbook containing account number and deposit ledger.',
        'Continue regular deposits annually for 15 years from account opening date.',
      ]),
      applicationStepsMr: JSON.stringify([
        'कोणत्याही नजीकच्या पोस्ट ऑफिस किंवा राष्ट्रीयीकृत बँकेतून सुकन्या समृद्धी अर्ज घ्या.',
        'मुलीचे नाव, जन्मदिनांक आणि पालकांचे केवायसी तपशील भरा.',
        'मुलीचा जन्म दाखला आणि पालकांचे आधार व पॅन कार्ड जोडा.',
        'किमान ₹२५० भरून खाते सुरू करा व सुकन्या पासबुक मिळवा.',
        'पुढील १५ वर्षे दरवर्षी किमान ₹२५० ते कमाल ₹१.५ लाखांपर्यंत जमा करत राहा.',
      ]),
      applicationStepsHi: JSON.stringify([
        'डाकघर या अधिकृत बैंक से सुकन्या समृद्धि खाता खोलने का फॉर्म प्राप्त करें।',
        'बालिका का जन्म प्रमाण पत्र और अभिभावक का आधार/पैन कार्ड संलग्न करें।',
        'न्यूनतम ₹250 की आरंभिक जमा राशि के साथ फॉर्म जमा करें।',
        'पासबुक प्राप्त करें और प्रति वर्ष आवश्यकतानुसार राशि जमा करें।',
      ]),
      importantNotesEn: 'Account matures after 21 years from opening date or upon marriage of girl child after turning 18. Partial withdrawal of 50% allowed for higher education at age 18.',
      importantNotesMr: 'खाते उघडल्यापासून २१ वर्षांनी किंवा मुलीच्या वयाच्या १८ वर्षानंतर लग्नावेळी परिपक्व होते. वयाच्या १८ व्या वर्षी शिक्षणासाठी ५०% रक्कम काढता येते.',
      importantNotesHi: 'बालिका के 18 वर्ष की आयु पूरी करने पर उच्च शिक्षा के लिए 50% तक राशि की निकासी की जा सकती है।',
      criteria: {
        minAge: 0,
        maxAge: 10,
        allowedGenders: JSON.stringify(['Female']),
        allowedStates: 'All India',
        allowedOccupations: 'Any',
        allowedEducation: 'Any',
        maxAnnualIncome: null,
        allowedCategories: 'Any',
        requiresDisability: false,
        requiresBpl: false,
        extraConditionsEn: 'Account must be opened before the girl child attains 10 years of age. Maximum 2 accounts per family (or 3 in case of twin girls).',
        extraConditionsMr: 'मुलीचे वय १० वर्षे पूर्ण होण्यापूर्वी खाते उघडणे आवश्यक. एका कुटुंबातील कमाल २ मुलींसाठी हे खाते उघडता येते.',
        extraConditionsHi: 'बालिका की आयु 10 वर्ष से कम होनी चाहिए। एक परिवार में अधिकतम 2 बालिकाओं के लिए खाता खोला जा सकता है।',
      },
      documents: [
        {
          nameEn: 'Girl Child Birth Certificate',
          nameMr: 'मुलीचा जन्म दाखला (नगरपालिका / ग्रामपंचायत)',
          nameHi: 'बालिका का जन्म प्रमाण पत्र',
          descriptionEn: 'Official birth certificate issued by municipal registrar.',
          descriptionMr: 'जन्म नोंदणी दाखला.',
          isMandatory: true,
          issuanceAuthority: 'Registrar of Births & Deaths',
          documentType: 'Identity',
        },
        {
          nameEn: 'Parent / Legal Guardian Aadhaar & PAN',
          nameMr: 'पालकांचे आधार कार्ड व पॅन कार्ड',
          nameHi: 'माता-पिता/अभिभावक का आधार और पैन',
          descriptionEn: 'Identity and address proof of the guardian.',
          descriptionMr: 'पालकांचा अधिकृत ओळख पुरावा.',
          isMandatory: true,
          issuanceAuthority: 'Govt of India',
          documentType: 'Identity',
        },
      ],
    },
    {
      slug: 'pradhan-mantri-awas-yojana-urban-gramin',
      titleEn: 'Pradhan Mantri Awas Yojana (PMAY Housing For All)',
      titleMr: 'प्रधानमंत्री आवास योजना (सर्वांसाठी पक्की घरे)',
      titleHi: 'प्रधानमंत्री आवास योजना (पीएमएवाई)',
      shortSummaryEn: 'Financial assistance of ₹1.2 Lakh to ₹2.67 Lakhs subsidy for building or purchasing a pucca house with basic amenities for EWS, LIG, and rural poor.',
      shortSummaryMr: 'आर्थिक दुर्बल आणि बेघर नागरिकांना स्वतःचे हक्काचे पक्के घर बांधण्यासाठी ₹१.२० लाख ते ₹२.६७ लाखांपर्यंत थेट अनुदान.',
      shortSummaryHi: 'बेघर और कच्चे मकानों में रहने वाले परिवारों को पक्का मकान बनाने के लिए ₹1.20 लाख से ₹2.67 लाख तक की वित्तीय सहायता।',
      detailedDescriptionEn: 'PMAY aims to provide affordable housing to all eligible families in urban (PMAY-U) and rural (PMAY-G) areas. Beneficiaries receive direct grants for rural house construction or interest subsidies up to ₹2.67 Lakhs on home loans under Credit Linked Subsidy Scheme (CLSS).',
      detailedDescriptionMr: 'केंद्र आणि राज्य शासनाच्या संयुक्त विद्यमाने ग्रामीण भागातील बेघर कुटुंबांना ₹१.२० लाखांचे थेट बांधकाम अनुदान दिले जाते. शहरी भागातील मध्यम व अल्प उत्पन्न गटातील नागरिकांना गृहकर्जावर व्याज अनुदान मिळते.',
      detailedDescriptionHi: 'प्रधानमंत्री आवास योजना के माध्यम से ग्रामीण और शहरी क्षेत्रों में पात्र लाभार्थियों को पक्के मकान के निर्माण अथवा खरीद हेतु सीधी आर्थिक सहायता प्रदान की जाती है।',
      benefitsEn: 'PMAY-Gramin: Direct DBT grant of ₹1,20,000 in plains / ₹1,30,000 in hilly areas + 90 days MGNREGA wages (₹25,000) + ₹12,000 for toilet. PMAY-Urban: Up to ₹2.67 Lakhs interest subsidy.',
      benefitsMr: 'ग्रामीण भागासाठी ₹१,२०,००० थेट बांधकाम अनुदान + रोजगार हमी योजनेतून ९० दिवसांचे मजुरी मानधन + ₹१२,००० शौचालय अनुदान.',
      benefitsHi: 'ग्रामीण क्षेत्रों में ₹1,20,000 प्रत्यक्ष अनुदान + मनरेगा मजदूरी + शौचालय निर्माण सहायता।',
      benefitType: 'Subsidy & Grant',
      department: 'Ministry of Rural Development / Ministry of Housing and Urban Affairs',
      level: 'CENTRAL',
      state: 'All India',
      categoryId: categories['housing-shelter'].id,
      sourceId: sources['Pradhan Mantri Awas Yojana - Urban & Gramin'].id,
      applicationMode: 'BOTH',
      applicationUrl: 'https://pmaymis.gov.in',
      portalName: 'PMAY-MIS / AwaasApp',
      applicationDeadline: 'Rolling / Phase Wise',
      isFeatured: false,
      applicationStepsEn: JSON.stringify([
        'For Rural: Contact your Gram Sevak or Village Panchayat to verify entry in Awaas+ priority list.',
        'Geotagging of existing kuccha house is carried out by the village nodal officer via AwaasApp.',
        'Sanction order issued by Block Development Officer (BDO).',
        'Installment 1 (₹40,000) released directly into bank account to start foundation construction.',
        'Subsequent installments released post geo-tagged inspection of lintel and roof levels.',
      ]),
      applicationStepsMr: JSON.stringify([
        'ग्रामीण भागासाठी: ग्रामपंचायत किंवा ग्रामसेवकाशी संपर्क साधून आवास+ प्रतीक्षा यादीतील नाव तपासा.',
        'नोडल अधिकाऱ्यामार्फत सध्याच्या कच्च्या घराचे जिओ-टॅगिंग (Geo-tagging) केले जाते.',
        'तालुका पंचायत समितीकडून मंजुरी आदेश मिळाल्यानंतर पहिला ₹४०,००० चा हप्ता थेट खात्यात जमा होतो.',
        'पाया, भिंती आणि छताचे बांधकाम झाल्यावर पुढील हप्ते तपासणीनंतर मिळतात.',
      ]),
      applicationStepsHi: JSON.stringify([
        'ग्राम पंचायत या नगर पालिका में आवास सूची में अपना नाम सत्यापित करें।',
        'अधिकारियों द्वारा वर्तमान कच्चे मकान का जियो-टैगिंग सत्यापन किया जाता है।',
        'स्वीकृति के बाद निर्माण कार्य हेतु किस्तों में राशि सीधे बैंक खाते में भेजी जाती है।',
      ]),
      importantNotesEn: 'The house must be co-owned or registered in the name of the female head of the family.',
      importantNotesMr: 'घर कुटुंबातील महिला प्रमुखाच्या नावावर किंवा संयुक्त नावावर असणे बंधनकारक आहे.',
      importantNotesHi: 'मकान का स्वामित्व परिवार की महिला मुखिया के नाम या संयुक्त नाम पर होना आवश्यक है।',
      criteria: {
        minAge: 21,
        maxAge: 75,
        allowedGenders: 'Any',
        allowedStates: 'All India',
        allowedOccupations: 'Any',
        allowedEducation: 'Any',
        maxAnnualIncome: 300000,
        allowedCategories: 'Any',
        requiresDisability: false,
        requiresBpl: true,
        extraConditionsEn: 'The beneficiary family must not own a pucca house anywhere in India.',
        extraConditionsMr: 'भारतात कुठेही स्वतःच्या किंवा कुटुंबातील सदस्यांच्या नावावर पक्के घर नसावे.',
        extraConditionsHi: 'देश में कहीं भी परिवार के किसी सदस्य के नाम पक्का मकान नहीं होना चाहिए।',
      },
      documents: [
        {
          nameEn: 'Aadhaar Card of all family members',
          nameMr: 'कुटुंबातील सर्व सदस्यांचे आधार कार्ड',
          nameHi: 'परिवार के सभी सदस्यों का आधार कार्ड',
          descriptionEn: 'Aadhaar copies for biometric linkage.',
          descriptionMr: 'सर्व सदस्यांची आधार प्रत.',
          isMandatory: true,
          issuanceAuthority: 'UIDAI',
          documentType: 'Identity',
        },
        {
          nameEn: 'Gram Panchayat / Ward Certificate of No Pucca House',
          nameMr: 'ग्रामपंचायत किंवा नगरपालिकेचे बेघर / कच्चे घर प्रमाणपत्र',
          nameHi: 'कच्चा मकान / बेघर होने का प्रमाण पत्र',
          descriptionEn: 'Certificate affirming applicant does not own a pucca house.',
          descriptionMr: 'पक्के घर नसल्याचा दाखला.',
          isMandatory: true,
          issuanceAuthority: 'Gram Sevak / Ward Officer',
          documentType: 'Other',
        },
        {
          nameEn: 'Bank Passbook (MGNREGA / DBT Enabled)',
          nameMr: 'बँक पासबुक प्रत',
          nameHi: 'डीबीटी सक्षम बैंक पासबुक',
          descriptionEn: 'Active single/joint bank account passbook.',
          descriptionMr: 'बँक खाते तपशील.',
          isMandatory: true,
          issuanceAuthority: 'Bank',
          documentType: 'Bank',
        },
      ],
    },
    {
      slug: 'national-apprenticeship-promotion-scheme-naps',
      titleEn: 'National Apprenticeship Promotion Scheme (NAPS)',
      titleMr: 'राष्ट्रीय शिकाऊ उमेदवारी प्रोत्साहन योजना (NAPS)',
      titleHi: 'राष्ट्रीय शिक्षुता प्रोत्साहन योजना (एनएपीएस)',
      shortSummaryEn: 'Government pays 25% of monthly stipend (up to ₹1,500/month) directly to ITI, Diploma, and Graduate apprentices undergoing industrial on-the-job training.',
      shortSummaryMr: 'औद्योगिक प्रशिक्षण घेणाऱ्या आयटीआय, पदविका व पदवीधर शिकाऊ उमेदवारांना दरमहा शासनाकडून थेट २५% (₹१,५०० पर्यंत) विद्यावेतन अनुदान.',
      shortSummaryHi: 'उद्योगों में व्यावहारिक प्रशिक्षण ले रहे आईटीआई, डिप्लोमा और स्नातक प्रशिक्षुओं को सरकार द्वारा ₹1,500 प्रति माह तक का प्रत्यक्ष वजीफा।',
      detailedDescriptionEn: 'NAPS aims to promote apprenticeship training in industry by providing financial support to enterprises and direct stipend subsidies to youth. Candidates gain real-world industry experience across engineering, manufacturing, retail, logistics, and IT sectors while earning a respectable monthly stipend.',
      detailedDescriptionMr: 'कौशल्य विकास व उद्योजकता मंत्रालयाची ही योजना असून युवकांना कारखान्यांमध्ये व कंपन्यांमध्ये प्रत्यक्ष कामाचा अनुभव मिळवून देण्यासाठी मासिक विद्यावेतन दिले जाते.',
      detailedDescriptionHi: 'युवाओं को उद्योगों में हैंड्स-ऑन ट्रेनिंग और अनुभव प्रदान करने के लिए यह राष्ट्रीय योजना चलाई जा रही है।',
      benefitsEn: 'Monthly stipend of ₹7,000 to ₹15,000 (with Govt DBT share up to ₹1,500/mo) + National Apprenticeship Certificate (NAC) recognized across India and abroad.',
      benefitsMr: 'दरमहा ₹७,००० ते ₹१५,००० विद्यावेतन + शासनाचे राष्ट्रीय शिकाऊ उमेदवारी प्रमाणपत्र (NAC).',
      benefitsHi: 'मासिक वजीफा + राष्ट्रीय शिक्षुता प्रमाण पत्र (एनएसी)।',
      benefitType: 'Training & Stipend',
      department: 'Ministry of Skill Development and Entrepreneurship',
      level: 'CENTRAL',
      state: 'All India',
      categoryId: categories['employment-skills'].id,
      sourceId: sources['Skill India Digital Hub'].id,
      applicationMode: 'ONLINE',
      applicationUrl: 'https://www.apprenticeshipindia.gov.in',
      portalName: 'Apprenticeship India Portal',
      applicationDeadline: 'Rolling / Year Round',
      isFeatured: false,
      applicationStepsEn: JSON.stringify([
        'Register on apprenticeshipindia.gov.in as a Candidate using email and Aadhaar.',
        'Complete profile details including education marks, ITI trade / Diploma stream, and resume.',
        'Search for Apprenticeship Opportunities by trade, industry, and preferred location.',
        'Click "Apply" on matching industry vacancies.',
        'Attend short interview/selection by the enterprise.',
        'Sign digital apprenticeship contract and receive monthly stipend via DBT.',
      ]),
      applicationStepsMr: JSON.stringify([
        'apprenticeshipindia.gov.in वर उमेदवार म्हणून आधार व ईमेलने नोंदणी करा.',
        'आयटीआय, डिप्लोमा किंवा पदवीचे गुण आणि प्रोफाइल भरा.',
        'आपल्या आवडीच्या कंपन्या व ट्रेडनुसार शिकाऊ उमेदवारी शोधून "Apply" वर क्लिक करा.',
        'कंपनीकडून निवड झाल्यानंतर डिजिटल करार स्वाक्षरी करा आणि विद्यावेतन मिळवा.',
      ]),
      applicationStepsHi: JSON.stringify([
        'apprenticeshipindia.gov.in पर उम्मीदवार के रूप में पंजीकरण करें।',
        'शैक्षणिक योग्यता विवरण भरें और संबंधित ट्रेड में अवसरों के लिए आवेदन करें।',
        'उद्योग द्वारा चयन के बाद अनुबंध पर हस्ताक्षर करें और मासिक वजीफा प्राप्त करें।',
      ]),
      importantNotesEn: 'Candidates must be minimum 14 years of age (18 for hazardous industries). No maximum age limit.',
      importantNotesMr: 'किमान वय १४ वर्षे पूर्ण असावे (धोकादायक उद्योगांसाठी १८ वर्षे).',
      importantNotesHi: 'न्यूनतम आयु 14 वर्ष होनी चाहिए।',
      criteria: {
        minAge: 14,
        maxAge: 35,
        allowedGenders: 'Any',
        allowedStates: 'All India',
        allowedOccupations: JSON.stringify(['Student', 'Unemployed']),
        allowedEducation: JSON.stringify(['10th Pass', '12th Pass', 'Diploma', 'Undergraduate']),
        maxAnnualIncome: null,
        allowedCategories: 'Any',
        requiresDisability: false,
        requiresBpl: false,
        extraConditionsEn: 'Must have completed 10th/12th/ITI/Diploma or Graduation in any discipline.',
        extraConditionsMr: '१० वी/१२ वी/आयटीआय किंवा पदविका उत्तीर्ण असणे आवश्यक.',
        extraConditionsHi: '10वीं/12वीं/आईटीआई/डिप्लोमा या स्नातक उत्तीर्ण होना आवश्यक है।',
      },
      documents: [
        {
          nameEn: 'Aadhaar Card',
          nameMr: 'आधार कार्ड',
          nameHi: 'आधार कार्ड',
          descriptionEn: 'Identity and age proof.',
          descriptionMr: 'ओळख पुरावा.',
          isMandatory: true,
          issuanceAuthority: 'UIDAI',
          documentType: 'Identity',
        },
        {
          nameEn: 'Educational Certificates (10th/ITI/Diploma/Degree)',
          nameMr: 'शैक्षणिक प्रमाणपत्रे व गुणपत्रिका',
          nameHi: 'शैक्षणिक अंकतालिका और प्रमाण पत्र',
          descriptionEn: 'Proof of qualifying examination.',
          descriptionMr: 'उत्तीर्ण परीक्षेची गुणपत्रिका.',
          isMandatory: true,
          issuanceAuthority: 'Board / University / NCVT',
          documentType: 'Education',
        },
        {
          nameEn: 'Bank Passbook / Cancelled Cheque',
          nameMr: 'बँक पासबुक किंवा रद्द केलेला धनादेश',
          nameHi: 'बैंक पासबुक / रद्द चेक',
          descriptionEn: 'Bank details for receiving Government stipend portion directly.',
          descriptionMr: 'थेट विद्यावेतन जमा होण्यासाठी बँक तपशील.',
          isMandatory: true,
          issuanceAuthority: 'Bank',
          documentType: 'Bank',
        },
      ],
    },
    {
      slug: 'sanjay-gandhi-niradhar-anudan-yojana',
      titleEn: 'Sanjay Gandhi Niradhar Anudan Yojana',
      titleMr: 'संजय गांधी निराधार अनुदान योजना (महाराष्ट्र शासन)',
      titleHi: 'संजय गांधी निराधार अनुदान योजना',
      shortSummaryEn: 'Monthly financial pension of ₹1,500 per month provided by Maharashtra Government to destitute persons, widows, divorced women, and persons with severe disabilities.',
      shortSummaryMr: 'निराधार व्यक्ती, विधवा महिला, घटस्फोटित स्त्रिया आणि गंभीर दिव्यांग व्यक्तींना दरमहा ₹१,५०० ची थेट पेन्शन मदत.',
      shortSummaryHi: 'निराश्रित व्यक्तियों, विधवाओं, तलाकशुदा महिलाओं और गंभीर दिव्यांगजनों को महाराष्ट्र सरकार द्वारा ₹1,500 प्रति माह की पेंशन।',
      detailedDescriptionEn: 'The Sanjay Gandhi Niradhar Anudan Yojana provides social security pension to destitute persons below poverty line, elderly above 65 with no source of livelihood, widows, orphans, transgender individuals, and persons suffering from major debilitating illnesses (cancer, TB, paralysis) or severe disability (40%+).',
      detailedDescriptionMr: 'महाराष्ट्र शासनाच्या सामाजिक न्याय व विशेष सहाय्य विभागामार्फत समाजातील दुर्बल, निराधार, विधवा व दिव्यांगांना सन्मानाने जगता यावे म्हणून दरमहा ₹१,५०० थेट बँक खात्यात दिले जातात.',
      detailedDescriptionHi: 'महाराष्ट्र सरकार द्वारा समाज के निराश्रित, बुजुर्ग, विधवा और दिव्यांगजनों को मासिक आर्थिक संबल प्रदान करने वाली प्रमुख सामाजिक सुरक्षा योजना।',
      benefitsEn: '₹1,500 monthly pension transferred directly via DBT to the beneficiary bank account on a recurring monthly basis.',
      benefitsMr: 'दरमहा ₹१,५०० थेट बँक खात्यात कायमस्वरूपी पेन्शन स्वरूपात जमा.',
      benefitsHi: '₹1,500 प्रति माह सीधे बैंक खाते में पेंशन के रूप में।',
      benefitType: 'Direct Benefit Transfer',
      department: 'Social Justice & Special Assistance Department, Govt of Maharashtra',
      level: 'STATE',
      state: 'Maharashtra',
      categoryId: categories['social-security-seniors'].id,
      sourceId: sources['Maharashtra Social Security Portal'].id,
      applicationMode: 'BOTH',
      applicationUrl: 'https://sjsa.maharashtra.gov.in',
      portalName: 'Aaple Sarkar / Tahsildar Sanjay Gandhi Yojana Desk',
      applicationDeadline: 'Rolling / Always Open',
      isFeatured: false,
      applicationStepsEn: JSON.stringify([
        'Obtain Sanjay Gandhi Niradhar application form from the Tahsildar office or Aaple Sarkar portal.',
        'Attach Age Proof, Income Certificate from Tehsildar (annual family income below ₹50,000), and Residence Proof (15 years in Maharashtra).',
        'Attach specific certificate: Widow death certificate of husband / Civil Surgeon Disability Certificate (40%+).',
        'Submit application at the Tahsildar Office (Sanjay Gandhi Yojana Desk).',
        'The Sanjay Gandhi Yojana Committee, chaired by local MLA/Tahsildar, reviews and sanctions the pension.',
        'Monthly pension commences via direct bank credit.',
      ]),
      applicationStepsMr: JSON.stringify([
        'तहसील कार्यालयातील संजय गांधी योजना शाखेतून किंवा ' + 'आपले सरकार' + ' पोर्टलवरून अर्ज घ्या.',
        'तहसीलदारांचा ₹५०,००० पेक्षा कमी उत्पन्नाचा दाखला आणि १५ वर्षे महाराष्ट्रात वास्तव्याचा पुरावा जोडा.',
        'विधवांसाठी पतीचा मृत्यू दाखला किंवा दिव्यांगांसाठी जिल्हा शल्यचिकित्सकांचे ४०% पेक्षा जास्त दिव्यांगत्व प्रमाणपत्र जोडा.',
        'तहसीलदार कार्यालयात अर्ज जमा करा. समितीच्या मंजुरीनंतर दरमहा ₹१,५०० बँक खात्यात सुरू होतात.',
      ]),
      applicationStepsHi: JSON.stringify([
        'तहसील कार्यालय से आवेदन पत्र प्राप्त करें या आपले सरकार पोर्टल से डाउनलोड करें।',
        'आय प्रमाण पत्र (₹50,000 से कम) और 15 वर्ष का अधिवास प्रमाण पत्र संलग्न करें।',
        'सत्यापन के बाद समिति द्वारा मासिक पेंशन स्वीकृत की जाती है।',
      ]),
      importantNotesEn: 'Applicant must have lived in Maharashtra for at least 15 continuous years.',
      importantNotesMr: 'अर्जदार सलग १५ वर्षे महाराष्ट्र राज्याचा रहिवासी असणे आवश्यक आहे.',
      importantNotesHi: 'आवेदक का कम से कम 15 वर्षों से महाराष्ट्र में निवास होना आवश्यक है।',
      criteria: {
        minAge: 18,
        maxAge: 100,
        allowedGenders: 'Any',
        allowedStates: 'Maharashtra',
        allowedOccupations: JSON.stringify(['Unemployed', 'Daily Wage', 'Other']),
        allowedEducation: 'Any',
        maxAnnualIncome: 50000,
        allowedCategories: 'Any',
        requiresDisability: false,
        requiresBpl: true,
        extraConditionsEn: 'Family income must not exceed ₹50,000 per annum. Must be destitute/widow/divorced/differently abled.',
        extraConditionsMr: 'कुटुंबाचे वार्षिक उत्पन्न ₹५०,००० पेक्षा कमी असावे आणि कमावता मुलगा/मुलगी नसावी.',
        extraConditionsHi: 'वार्षिक आय ₹50,000 से कम होनी चाहिए।',
      },
      documents: [
        {
          nameEn: 'Tehsildar Income Certificate (Below ₹50,000)',
          nameMr: 'तहसीलदार कार्यालयाचा उत्पन्नाचा दाखला (वार्षिक ₹५०,००० आत)',
          nameHi: 'आय प्रमाण पत्र (₹50,000 से कम)',
          descriptionEn: 'Valid annual income certificate showing destitute status.',
          descriptionMr: 'सक्षम अधिकाऱ्याचा उत्पन्नाचा दाखला.',
          isMandatory: true,
          issuanceAuthority: 'Tehsildar',
          documentType: 'Income',
        },
        {
          nameEn: '15-Year Domicile / Residence Proof in Maharashtra',
          nameMr: '१५ वर्षे महाराष्ट्रात वास्तव्याचा पुरावा',
          nameHi: '15 वर्ष का निवास प्रमाण पत्र',
          descriptionEn: 'Domicile or continuous ration card/voter record proof.',
          descriptionMr: 'अधिवास प्रमाणपत्र किंवा जुने रेशन कार्ड.',
          isMandatory: true,
          issuanceAuthority: 'Revenue Authority',
          documentType: 'Domicile',
        },
        {
          nameEn: 'Supporting Condition Certificate (Disability/Death/Divorce)',
          nameMr: 'संबंधित विशेष प्रमाणपत्र (दिव्यांगत्व दाखला / पतीचा मृत्यू दाखला)',
          nameHi: 'संबंधित प्रमाण पत्र (दिव्यांगता/मृत्यु प्रमाण पत्र)',
          descriptionEn: 'Civil Surgeon Disability Certificate (40%+) or husband death certificate for widows.',
          descriptionMr: 'जिल्हा रुग्णालयाचा ४०% दिव्यांग दाखला किंवा मृत्यू दाखला.',
          isMandatory: true,
          issuanceAuthority: 'Civil Hospital / Municipal Corp',
          documentType: 'Other',
        },
        {
          nameEn: 'Bank Account Passbook (Single Account)',
          nameMr: 'बँक पासबुक प्रत',
          nameHi: 'बैंक पासबुक',
          descriptionEn: 'Aadhaar seeded bank account in nationalized/post office bank.',
          descriptionMr: 'बँक खाते तपशील.',
          isMandatory: true,
          issuanceAuthority: 'Bank',
          documentType: 'Bank',
        },
      ],
    },
  ];

  for (const sData of schemesData) {
    const { criteria, documents, ...schemeFields } = sData;
    const scheme = await prisma.scheme.create({
      data: {
        ...schemeFields,
        eligibilityCriteria: {
          create: criteria,
        },
        requiredDocuments: {
          create: documents,
        },
      },
    });
    console.log(`✅ Seeded scheme: ${scheme.titleEn}`);
  }

  // 6. Create Seed Applications and Saved Schemes for the citizen user
  const mahadbtScheme = await prisma.scheme.findUnique({
    where: { slug: 'mahadbt-post-matric-scholarship-obc-ebc' },
    include: { requiredDocuments: true },
  });

  const pmkisanScheme = await prisma.scheme.findUnique({
    where: { slug: 'pm-kisan-samman-nidhi' },
  });

  const mudraScheme = await prisma.scheme.findUnique({
    where: { slug: 'pradhan-mantri-mudra-yojana-pmmy' },
  });

  if (mahadbtScheme) {
    // Save scheme for user
    await prisma.savedScheme.create({
      data: {
        userId: citizen.id,
        schemeId: mahadbtScheme.id,
        notes: 'Targeting fee waiver for B.E. 2nd Year admission.',
      },
    });

    // Create an active application with document progress
    const docProgress: Record<string, string> = {};
    mahadbtScheme.requiredDocuments.forEach((doc, idx) => {
      docProgress[doc.id] = idx < 3 ? 'READY' : 'MISSING';
    });

    const app = await prisma.application.create({
      data: {
        userId: citizen.id,
        schemeId: mahadbtScheme.id,
        status: 'DOCUMENTS_PENDING',
        referenceNumber: 'MH-DBT-2026-89421',
        appliedDate: new Date('2026-08-10'),
        deadlineDate: new Date('2026-08-31'),
        notes: 'Income certificate renewed. Awaiting Domicile certificate from Tehsildar desk.',
        documentProgressJson: JSON.stringify(docProgress),
      },
    });

    // Create notification for impending deadline
    await prisma.notification.create({
      data: {
        userId: citizen.id,
        titleEn: 'Application Deadline Approaching',
        titleMr: 'अर्जाची अंतिम मुदत जवळ येत आहे',
        titleHi: 'आवेदन की अंतिम तिथि निकट आ रही है',
        messageEn: 'MahaDBT Post-Matric Scholarship application for 2026 closes on August 31st. 2 documents are still marked missing in your checklist.',
        messageMr: 'महाडीबीटी मॅट्रिकोत्तर शिष्यवृत्ती अर्जाची अंतिम मुदत ३१ ऑगस्ट आहे. आपल्या चेकलिस्टमध्ये अद्याप २ कागदपत्रे प्रलंबित आहेत.',
        messageHi: 'महाडीबीटी पोस्ट-मैट्रिक छात्रवृत्ति की अंतिम तिथि 31 अगस्त है। आपकी चेकलिस्ट में 2 दस्तावेज अभी भी लंबित हैं।',
        type: 'DEADLINE',
        relatedSchemeId: mahadbtScheme.id,
        relatedApplicationId: app.id,
        isRead: false,
      },
    });
  }

  if (mudraScheme) {
    await prisma.savedScheme.create({
      data: {
        userId: citizen.id,
        schemeId: mudraScheme.id,
        notes: 'Exploring for laptop and robotics project startup.',
      },
    });
  }

  // 7. Create an initial sample report to show in Admin dashboard
  if (pmkisanScheme) {
    await prisma.report.create({
      data: {
        userId: citizen.id,
        schemeId: pmkisanScheme.id,
        issueType: 'OUTDATED_DEADLINE',
        description: 'The portal shows the 18th installment release date as tentative. Please update the official announcement dates.',
        userEmail: citizen.email,
        status: 'PENDING',
        adminNotes: '',
      },
    });
  }

  // 8. Create sample AI conversation for history
  const sampleConv = await prisma.aIConversation.create({
    data: {
      userId: citizen.id,
      title: 'Maharashtra OBC Scholarships Inquiry',
      language: 'en',
      messages: {
        create: [
          {
            sender: 'USER',
            content: 'I am a 20 year old student from Pune pursuing B.E. Computer Engineering with family income ₹1.8 Lakhs. Which government scholarships can I apply for?',
          },
          {
            sender: 'ASSISTANT',
            content: 'Based on your profile as a 20-year-old student in Maharashtra with an annual family income under ₹2.5 Lakhs (OBC category), you are **Likely Eligible** for the **MahaDBT Post-Matric Scholarship for OBC & EBC Students**.\n\n### Key Benefits:\n- 100% Tuition Fee & Exam Fee reimbursement directly deposited via DBT.\n- Maintenance allowance up to ₹1,200/month.\n\n### Next Steps:\n1. Ensure your Aadhaar is linked to your bank account via NPCI.\n2. Obtain an Income Certificate from the Tehsildar.\n3. Apply on the official MahaDBT portal (mahadbt.maharashtra.gov.in).\n\n*Note: Official eligibility is subject to CAP allotment verification on the government portal.*',
            referencedSchemesJson: JSON.stringify([
              {
                id: mahadbtScheme?.id,
                slug: 'mahadbt-post-matric-scholarship-obc-ebc',
                title: 'MahaDBT Post-Matric Scholarship for OBC & EBC Students',
                benefit: 'Full Tuition & Exam Fee Reimbursement',
              },
            ]),
          },
        ],
      },
    },
  });

  console.log('✅ Database seeded successfully with realistic civic data!');
}

main()
  .catch((e) => {
    console.error('❌ Error during database seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
