import { Scheme, SchemeCategory, GovernmentSource } from '../types';

export const FALLBACK_CATEGORIES: SchemeCategory[] = [
  {
    id: 'cat-1',
    slug: 'scholarships-education',
    nameEn: 'Education & Scholarships',
    nameMr: 'शिक्षण आणि शिष्यवृत्ती',
    nameHi: 'शिक्षा और छात्रवृत्ति',
    icon: 'GraduationCap',
    descriptionEn: 'Scholarships, fee concessions, and education loans.',
    descriptionMr: 'विद्यार्थ्यांसाठी शिष्यवृत्ती आणि फी सवलत.',
    descriptionHi: 'छात्रों के लिए छात्रवृत्ति और शुल्क छूट।',
    displayOrder: 1,
    schemeCount: 3,
  },
  {
    id: 'cat-2',
    slug: 'agriculture-farmers',
    nameEn: 'Agriculture & Farmers',
    nameMr: 'कृषी आणि शेतकरी कल्याण',
    nameHi: 'कृषि और किसान कल्याण',
    icon: 'Tractor',
    descriptionEn: 'Crop insurance, input subsidies, and direct income support.',
    descriptionMr: 'शेतकऱ्यांसाठी पीक विमा आणि थेट आर्थिक मदत.',
    descriptionHi: 'किसानों के लिए फसल बीमा और प्रत्यक्ष आय सहायता।',
    displayOrder: 2,
    schemeCount: 2,
  },
  {
    id: 'cat-3',
    slug: 'healthcare-wellness',
    nameEn: 'Healthcare & Wellness',
    nameMr: 'आरोग्य आणि वैद्यकीय साहाय्य',
    nameHi: 'स्वास्थ्य और कल्याण',
    icon: 'HeartPulse',
    descriptionEn: 'Free hospitalization and ₹5 Lakh health insurance card.',
    descriptionMr: '₹५ लाखांपर्यंत मोफत उपचार आणि आरोग्य विमा कार्ड.',
    descriptionHi: '₹5 लाख तक का मुफ्त स्वास्थ्य बीमा और इलाज।',
    displayOrder: 3,
    schemeCount: 1,
  },
  {
    id: 'cat-4',
    slug: 'business-msme',
    nameEn: 'MSME & Entrepreneurship',
    nameMr: 'उद्योग आणि स्वयंरोजगार',
    nameHi: 'एमएसएमई और उद्यमिता',
    icon: 'Briefcase',
    descriptionEn: 'Collateral-free business loans up to ₹20 Lakhs.',
    descriptionMr: 'विनातारण ₹२० लाखांपर्यंत व्यवसाय कर्ज.',
    descriptionHi: '₹20 लाख तक का संपार्श्विक-मुक्त व्यावसायिक ऋण।',
    displayOrder: 4,
    schemeCount: 2,
  },
  {
    id: 'cat-5',
    slug: 'women-child',
    nameEn: 'Women & Child Welfare',
    nameMr: 'महिला आणि बालविकास',
    nameHi: 'महिला एवं बाल विकास',
    icon: 'Users',
    descriptionEn: 'Girl child financial security and maternity benefits.',
    descriptionMr: 'मुलींचे उज्ज्वल भविष्य आणि मातृत्व लाभ योजना.',
    descriptionHi: 'बालिका वित्तीय सुरक्षा और मातृत्व लाभ।',
    displayOrder: 5,
    schemeCount: 1,
  },
  {
    id: 'cat-6',
    slug: 'housing-shelter',
    nameEn: 'Housing & Shelter',
    nameMr: 'गृहनिर्माण आणि निवारा',
    nameHi: 'आवास और आश्रय',
    icon: 'Home',
    descriptionEn: 'Pucca house construction grants and interest subsidies.',
    descriptionMr: 'पक्के घर बांधणीसाठी थेट अनुदान.',
    descriptionHi: 'पक्का मकान निर्माण के लिए वित्तीय सहायता।',
    displayOrder: 6,
    schemeCount: 1,
  },
  {
    id: 'cat-7',
    slug: 'employment-skills',
    nameEn: 'Skill Development & Jobs',
    nameMr: 'कौशल्य विकास आणि रोजगार',
    nameHi: 'कौशल विकास और रोजगार',
    icon: 'Wrench',
    descriptionEn: 'Technical training and government apprenticeship stipends.',
    descriptionMr: 'मोफत तांत्रिक प्रशिक्षण व शिकाऊ उमेदवारी विद्यावेतन.',
    descriptionHi: 'कौशल प्रशिक्षण और शिक्षुता वजीफा।',
    displayOrder: 7,
    schemeCount: 2,
  },
  {
    id: 'cat-8',
    slug: 'social-security-seniors',
    nameEn: 'Senior Citizens & Pension',
    nameMr: 'ज्येष्ठ नागरिक आणि पेन्शन',
    nameHi: 'वरिष्ठ नागरिक और पेंशन',
    icon: 'ShieldCheck',
    descriptionEn: 'Monthly pensions for destitute, widows, and elderly.',
    descriptionMr: 'निराधार, विधवा आणि ज्येष्ठांसाठी मासिक पेन्शन.',
    descriptionHi: 'निराश्रितों और बुजुर्गों के लिए मासिक पेंशन।',
    displayOrder: 8,
    schemeCount: 1,
  },
];

export const FALLBACK_SOURCES: GovernmentSource[] = [
  {
    id: 'src-1',
    name: 'MahaDBT Official Portal',
    domain: 'mahadbt.maharashtra.gov.in',
    officialUrl: 'https://mahadbt.maharashtra.gov.in',
    portalName: 'MahaDBT Portal (Government of Maharashtra)',
    departmentName: 'Social Justice & Special Assistance Department',
    level: 'STATE',
    state: 'Maharashtra',
    isVerified: true,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'src-2',
    name: 'PM Kisan Samman Nidhi Portal',
    domain: 'pmkisan.gov.in',
    officialUrl: 'https://pmkisan.gov.in',
    portalName: 'PM-Kisan Official Portal',
    departmentName: 'Ministry of Agriculture and Farmers Welfare',
    level: 'CENTRAL',
    state: 'All India',
    isVerified: true,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
  },
];

export const FALLBACK_SCHEMES: Scheme[] = [
  {
    id: 'sch-1',
    slug: 'mahadbt-post-matric-scholarship-obc-ebc',
    titleEn: 'MahaDBT Post-Matric Scholarship for OBC & EBC Students',
    titleMr: 'महाडीबीटी मॅट्रिकोत्तर शिष्यवृत्ती योजना (इमाव व इबीसी)',
    titleHi: 'महाडीबीटी पोस्ट-मैट्रिक छात्रवृत्ति (ओबीसी और ईबीसी)',
    shortSummaryEn: '100% tuition and exam fee reimbursement plus monthly maintenance allowance for post-SSC diploma/degree students in Maharashtra.',
    shortSummaryMr: 'महाराष्ट्रातील पदवी व पदविका विद्यार्थ्यांसाठी संपूर्ण शिक्षण शुल्क, परीक्षा फी परतावा आणि निर्वाह भत्ता.',
    shortSummaryHi: 'महाराष्ट्र में उच्च शिक्षा प्राप्त कर रहे ओबीसी और ईबीसी छात्रों के लिए पूर्ण शिक्षण शुल्क प्रतिपूर्ति और निर्वाह भत्ता।',
    detailedDescriptionEn: 'The Government of Maharashtra provides financial assistance to students belonging to Other Backward Classes (OBC) and Economically Backward Classes (EBC) pursuing post-matriculation courses in recognized colleges across Maharashtra. The scheme pays reimbursement directly into student and college bank accounts via DBT.',
    detailedDescriptionMr: 'महाराष्ट्र शासनाच्या इतर मागास बहुजन कल्याण विभागामार्फत राज्यातील मान्यताप्राप्त महाविद्यालयांमध्ये पदविका, पदवी किंवा पदव्युत्तर शिक्षण घेणाऱ्या इतर मागासवर्गीय (OBC) आणि आर्थिकदृष्ट्या मागास (EBC) विद्यार्थ्यांच्या शिक्षणाचा खर्च हलका करण्यासाठी ही शिष्यवृत्ती दिली जाते.',
    detailedDescriptionHi: 'महाराष्ट्र सरकार अन्य पिछड़ा वर्ग (ओबीसी) और आर्थिक रूप से कमजोर वर्ग (ईबीसी) के छात्रों को उच्च शिक्षा जारी रखने के लिए डीबीटी के माध्यम से सीधे शुल्क प्रतिपूर्ति प्रदान करती है।',
    benefitsEn: 'Full Tuition Fee Reimbursement + Exam Fee waiver + Monthly Maintenance Allowance up to ₹1,200/month for hostellers and ₹600/month for day scholars.',
    benefitsMr: 'संपूर्ण शिक्षण शुल्क परतावा + परीक्षा फी सवलत + वसतिगृहातील विद्यार्थ्यांसाठी ₹१,२००/महिना आणि डे-स्कॉलर्ससाठी ₹६००/महिना निर्वाह भत्ता.',
    benefitsHi: 'पूर्ण शिक्षण शुल्क प्रतिपूर्ति + परीक्षा शुल्क माफी + ₹1,200 प्रति माह तक का निर्वाह भत्ता।',
    benefitType: 'Direct Benefit Transfer',
    department: 'Other Backward Bahujan Kalyan Department, Govt of Maharashtra',
    level: 'STATE',
    state: 'Maharashtra',
    categoryId: 'cat-1',
    category: FALLBACK_CATEGORIES[0],
    sourceId: 'src-1',
    source: FALLBACK_SOURCES[0],
    applicationMode: 'ONLINE',
    applicationUrl: 'https://mahadbt.maharashtra.gov.in',
    portalName: 'MahaDBT Portal (mahadbt.maharashtra.gov.in)',
    applicationDeadline: '31st March 2026',
    isFeatured: true,
    isPublished: true,
    viewsCount: 1420,
    savesCount: 384,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    isSaved: true,
    applicationStepsEn: JSON.stringify([
      'Visit official MahaDBT portal (mahadbt.maharashtra.gov.in) and register using Aadhaar OTP.',
      'Complete Profile section with personal, address, caste, income, and previous qualification details.',
      'Upload scanned documents: Domicile, Income Certificate (Tehsildar), Caste Certificate, and Marksheets.',
      'Navigate to "Other Backward Bahujan Kalyan Dept" schemes and select "Post Matric Scholarship to OBC Students".',
      'Select your current pursuing course, college name, and CAP allotment letter details.',
      'Submit application and save the Application ID for college desk verification.',
    ]),
    applicationStepsMr: JSON.stringify([
      'अधिकृत महाडीबीटी पोर्टलवर (mahadbt.maharashtra.gov.in) जाऊन आधार ओटीपी द्वारे नोंदणी करा.',
      'वैयक्तिक, पत्ता, जात, उत्पन्न आणि शैक्षणिक माहिती भरून प्रोफाइल पूर्ण करा.',
      'आवश्यक कागदपत्रे (उत्पन्न दाखला, जात प्रमाणपत्र, अधिवास प्रमाणपत्र आणि गुणपत्रिका) अपलोड करा.',
      'इतर मागास बहुजन कल्याण विभाग निवडून "मॅट्रिकोत्तर शिष्यवृत्ती" योजनेवर क्लिक करा.',
      'सध्याचा अभ्यासक्रम, कॉलेजचे नाव व कॅप प्रवेश पत्र निवडा.',
      'अर्ज सबमिट करा व ॲप्लिकेशन आयडी कॉलेज पडताळणीसाठी जतन करा.',
    ]),
    applicationStepsHi: JSON.stringify([
      'आधिकारिक महाडीबीटी पोर्टल पर जाएं और आधार ओटीपी से पंजीकरण करें।',
      'प्रोफाइल सेक्शन में व्यक्तिगत, जाति, आय और शैक्षणिक विवरण भरें।',
      'दस्तावेज अपलोड करें: आय प्रमाण पत्र, जाति प्रमाण पत्र, अधिवास प्रमाण पत्र और अंकतालिका।',
      'योजना का चयन करें और आवेदन जमा करें।',
    ]),
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 35,
      allowedGenders: 'Any',
      allowedStates: 'Maharashtra',
      allowedOccupations: JSON.stringify(['Student']),
      allowedEducation: JSON.stringify(['10th Pass', '12th Pass', 'Diploma', 'Undergraduate', 'Post Graduate']),
      maxAnnualIncome: 150000,
      allowedCategories: JSON.stringify(['OBC', 'SBC', 'VJNT', 'EWS']),
      requiresDisability: false,
      requiresBpl: false,
      extraConditionsEn: 'Must be a resident of Maharashtra admitted via CAP / Merit.',
    },
    requiredDocuments: [
      {
        id: 'doc-1',
        schemeId: 'sch-1',
        nameEn: 'Income Certificate from Tehsildar (Below ₹1.5L)',
        nameMr: 'तहसीलदार कार्यालयाचा उत्पन्नाचा दाखला',
        nameHi: 'तहसीलदार द्वारा जारी आय प्रमाण पत्र',
        descriptionEn: 'Current financial year certificate showing family income under ₹1.5 - 8 Lakhs.',
        isMandatory: true,
        issuanceAuthority: 'Tehsildar / Revenue Department',
        documentType: 'Income',
      },
      {
        id: 'doc-2',
        schemeId: 'sch-1',
        nameEn: 'Caste Certificate & Validity',
        nameMr: 'जात प्रमाणपत्र व पडताळणी प्रमाणपत्र',
        nameHi: 'जाति प्रमाण पत्र और वैधता',
        descriptionEn: 'Valid Maharashtra OBC/EWS caste certificate.',
        isMandatory: true,
        issuanceAuthority: 'Sub-Divisional Magistrate',
        documentType: 'Identity',
      },
      {
        id: 'doc-3',
        schemeId: 'sch-1',
        nameEn: 'Maharashtra Domicile Certificate',
        nameMr: 'महाराष्ट्र अधिवास दाखला (Domicile)',
        nameHi: 'महाराष्ट्र निवास प्रमाण पत्र',
        descriptionEn: 'Proof of continuous residence in Maharashtra.',
        isMandatory: true,
        issuanceAuthority: 'Tehsildar Office',
        documentType: 'Domicile',
      },
      {
        id: 'doc-4',
        schemeId: 'sch-1',
        nameEn: 'Aadhaar Card linked to Bank Account (NPCI Seeded)',
        nameMr: 'आधार कार्ड (बँक खात्याशी संलग्न)',
        nameHi: 'आधार कार्ड (बैंक खाते से लिंक)',
        descriptionEn: 'Bank passbook copy with NPCI DBT mapping active.',
        isMandatory: true,
        issuanceAuthority: 'UIDAI / Nationalized Bank',
        documentType: 'Bank',
      },
    ],
  },
  {
    id: 'sch-2',
    slug: 'pm-kisan-samman-nidhi',
    titleEn: 'PM Kisan Samman Nidhi Yojana',
    titleMr: 'प्रधानमंत्री किसान सन्मान निधी योजना',
    titleHi: 'प्रधानमंत्री किसान सम्मान निधि योजना',
    shortSummaryEn: 'Direct income support of ₹6,000 per year in 3 equal installments of ₹2,000 to all landholding farmer families.',
    shortSummaryMr: 'शेतकरी कुटुंबांना दरवर्षी ₹६,००० ची थेट आर्थिक मदत (दर ४ महिन्यांनी ₹२,००० चे तीन समान हप्ते).',
    shortSummaryHi: 'सभी पात्र किसान परिवारों को प्रति वर्ष ₹6,000 की प्रत्यक्ष आय सहायता।',
    detailedDescriptionEn: 'PM-KISAN provides income support of ₹6,000/- per year in three equal installments to all landholding farmer families across India to meet agricultural and domestic needs.',
    detailedDescriptionMr: 'प्रधानमंत्री किसान सन्मान निधी ही केंद्र शासनाची महत्त्वाकांक्षी योजना असून याद्वारे शेतकरी कुटुंबांना शेती निविष्ठा, बियाणे, खते खरेदी करण्यासाठी वार्षिक ₹६,००० थेट बँक खात्यात पाठवले जातात.',
    detailedDescriptionHi: 'प्रधानमंत्री किसान सम्मान निधि के तहत किसानों को कृषि और घरेलू जरूरतों के लिए प्रति वर्ष ₹6,000 तीन किस्तों में दिए जाते हैं।',
    benefitsEn: '₹6,000 annually credited directly to Aadhaar-seeded bank accounts via DBT in 3 installments.',
    benefitsMr: 'वार्षिक ₹६,००० थेट बँक खात्यात जमा (दर चार महिन्यांनी ₹२,००० चे तीन हप्ते).',
    benefitsHi: '₹6,000 प्रति वर्ष डीबीटी के माध्यम से सीधे बैंक खाते में।',
    benefitType: 'Direct Benefit Transfer',
    department: 'Ministry of Agriculture and Farmers Welfare, Govt of India',
    level: 'CENTRAL',
    state: 'All India',
    categoryId: 'cat-2',
    category: FALLBACK_CATEGORIES[1],
    sourceId: 'src-2',
    source: FALLBACK_SOURCES[1],
    applicationMode: 'ONLINE',
    applicationUrl: 'https://pmkisan.gov.in',
    portalName: 'PM-Kisan Portal (pmkisan.gov.in)',
    applicationDeadline: 'Rolling / Always Open',
    isFeatured: true,
    isPublished: true,
    viewsCount: 2310,
    savesCount: 512,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    applicationStepsEn: JSON.stringify([
      'Visit official PM-Kisan portal (pmkisan.gov.in) and click "New Farmer Registration".',
      'Enter Aadhaar number, Mobile number, and verify OTP.',
      'Enter 7/12 Land Record and Khata/Khatauni details.',
      'Submit application and complete mandatory e-KYC.',
    ]),
    applicationStepsMr: JSON.stringify([
      'pmkisan.gov.in वर जाऊन "New Farmer Registration" निवडा.',
      'आधार व मोबाईल नंबर टाकून ओटीपी पडताळणी करा.',
      '७/१२ जमिनीचा उतारा आणि खाते क्रमांक भरा.',
      'अर्ज सादर करा व ई-केवायसी (e-KYC) पूर्ण करा.',
    ]),
    applicationStepsHi: JSON.stringify([
      'pmkisan.gov.in पर जाएं और किसान पंजीकरण चुनें।',
      'आधार और जमीन के भू-अभिलेख विवरण दर्ज करें।',
    ]),
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 100,
      allowedGenders: 'Any',
      allowedStates: 'All India',
      allowedOccupations: JSON.stringify(['Farmer']),
      allowedEducation: 'Any',
      maxAnnualIncome: 800000,
      allowedCategories: 'Any',
      requiresDisability: false,
      requiresBpl: false,
    },
    requiredDocuments: [
      {
        id: 'doc-201',
        schemeId: 'sch-2',
        nameEn: '7/12 (Satbara) & 8-A Land Record Extract',
        nameMr: 'जमिनीचा चालू ७/१२ आणि ८-अ उतारा',
        nameHi: 'जमीन का खतौनी/भू-अभिलेख रिकॉर्ड',
        descriptionEn: 'Current land ownership document reflecting applicant name.',
        isMandatory: true,
        issuanceAuthority: 'Revenue Department / Mahabhulekh',
        documentType: 'Land',
      },
      {
        id: 'doc-202',
        schemeId: 'sch-2',
        nameEn: 'Aadhaar Card (Linked with Bank)',
        nameMr: 'आधार कार्ड (बँकेशी जोडलेले)',
        nameHi: 'आधार कार्ड',
        descriptionEn: 'Aadhaar copy with mobile OTP verification.',
        isMandatory: true,
        issuanceAuthority: 'UIDAI',
        documentType: 'Identity',
      },
    ],
  },
  {
    id: 'sch-3',
    slug: 'ayushman-bharat-pm-jay-health-card',
    titleEn: 'Ayushman Bharat PM-JAY (Golden Health Card)',
    titleMr: 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (आरोग्य कार्ड)',
    titleHi: 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (गोल्डन कार्ड)',
    shortSummaryEn: 'Cashless health insurance coverage up to ₹5,00,000 per family per year for hospitalization across 28,000+ empaneled hospitals.',
    shortSummaryMr: 'कुटुंबासाठी दरवर्षी ₹५,००,००० पर्यंत मोफत आणि कॅशलेस उपचार (२८,००० हून अधिक सरकारी व खाजगी रुग्णालयांमध्ये).',
    shortSummaryHi: 'प्रति परिवार प्रति वर्ष ₹5,00,000 तक का मुफ्त कैशलेस स्वास्थ्य बीमा।',
    detailedDescriptionEn: 'Ayushman Bharat PM-JAY provides health cover of ₹5 Lakh per family per year for secondary and tertiary care hospitalization to over 12 crore poor and vulnerable families.',
    detailedDescriptionMr: 'पात्र नागरिकांना गंभीर आजारांवर ₹५ लाखांपर्यंत मोफत उपचार मिळतात. यामध्ये औषधोपचार, शस्त्रक्रिया आणि रुग्णालयात भरतीचा खर्च समाविष्ट आहे.',
    detailedDescriptionHi: 'देश के 55 करोड़ से अधिक नागरिकों को अस्पताल में भर्ती होने पर 5 लाख रुपये तक का कैशलेस इलाज मुफ्त मिलता है।',
    benefitsEn: 'Cashless hospital treatment up to ₹5 Lakhs/year including surgeries, ICU, medicines, and pre/post hospitalization.',
    benefitsMr: 'वार्षिक ₹५ लाख रुपयांपर्यंत मोफत उपचार, शस्त्रक्रिया, औषधे आणि कॅशलेस सुविधा.',
    benefitsHi: 'प्रति वर्ष ₹5 लाख तक का कैशलेस अस्पताल उपचार और दवाएं।',
    benefitType: 'Health Insurance',
    department: 'National Health Authority, Ministry of Health and Family Welfare',
    level: 'CENTRAL',
    state: 'All India',
    categoryId: 'cat-3',
    category: FALLBACK_CATEGORIES[2],
    applicationMode: 'BOTH',
    applicationUrl: 'https://beneficiary.nha.gov.in',
    portalName: 'Ayushman Beneficiary Portal (beneficiary.nha.gov.in)',
    applicationDeadline: 'Rolling / Always Open',
    isFeatured: true,
    isPublished: true,
    viewsCount: 3100,
    savesCount: 680,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    applicationStepsEn: JSON.stringify([
      'Visit beneficiary.nha.gov.in or open Ayushman App.',
      'Search by Aadhaar Number or Ration Card.',
      'Complete Aadhaar e-KYC using OTP or Face Authentication.',
      'Download the Ayushman Golden PVC Card and present at any empaneled hospital.',
    ]),
    applicationStepsMr: JSON.stringify([
      'beneficiary.nha.gov.in वर जाऊन आधार किंवा रेशनकार्ड नंबर टाका.',
      'ई-केवायसी (e-KYC) पूर्ण करून कार्ड डाऊनलोड करा.',
    ]),
    applicationStepsHi: JSON.stringify([
      'beneficiary.nha.gov.in पर जाएं और आधार से ई-केवाईसी पूरी करके कार्ड डाउनलोड करें।',
    ]),
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 100,
      allowedGenders: 'Any',
      allowedStates: 'All India',
      allowedOccupations: 'Any',
      allowedEducation: 'Any',
      maxAnnualIncome: 300000,
      allowedCategories: 'Any',
      requiresDisability: false,
      requiresBpl: false,
    },
    requiredDocuments: [
      {
        id: 'doc-301',
        schemeId: 'sch-3',
        nameEn: 'Aadhaar Card',
        nameMr: 'आधार कार्ड',
        nameHi: 'आधार कार्ड',
        descriptionEn: 'Aadhaar of all family members.',
        isMandatory: true,
        issuanceAuthority: 'UIDAI',
        documentType: 'Identity',
      },
      {
        id: 'doc-302',
        schemeId: 'sch-3',
        nameEn: 'Ration Card (Yellow / Orange / NFSA)',
        nameMr: 'रेशन कार्ड (पिवळे किंवा केशरी शिधापत्रिका)',
        nameHi: 'राशन कार्ड',
        descriptionEn: 'Public Distribution ration card.',
        isMandatory: true,
        issuanceAuthority: 'Food & Civil Supplies Dept',
        documentType: 'Identity',
      },
    ],
  },
  {
    id: 'sch-4',
    slug: 'pradhan-mantri-mudra-yojana-pmmy',
    titleEn: 'Pradhan Mantri MUDRA Yojana (PMMY)',
    titleMr: 'प्रधानमंत्री मुद्रा योजना (PMMY स्वयंरोजगार कर्ज)',
    titleHi: 'प्रधानमंत्री मुद्रा योजना (पीएमएमवाई)',
    shortSummaryEn: 'Collateral-free business loans up to ₹20,00,000 for shopkeepers, artisans, and new startups under Shishu, Kishore, and Tarun categories.',
    shortSummaryMr: 'लघु व सूक्ष्म उद्योजक, व्यावसायिक, दुकानदार यांच्यासाठी विनातारण ₹२० लाखांपर्यंत व्यवसाय कर्ज.',
    shortSummaryHi: 'सूक्ष्म और लघु उद्यमों के लिए ₹20 लाख तक का संपार्श्विक-मुक्त व्यावसायिक ऋण।',
    detailedDescriptionEn: 'PMMY enables micro and small non-corporate, non-farm enterprises to access collateral-free institutional credit.',
    detailedDescriptionMr: 'सूक्ष्म, लघु व मध्यम उद्योग सुरू करण्यासाठी किंवा वाढवण्यासाठी बँकांमार्फत विनातारण सुलभ कर्ज पुरवठा केला जातो.',
    detailedDescriptionHi: 'पीएमएमवाई गैर-कॉर्पोरेट लघु उद्यमों को आय सृजन के लिए 20 लाख रुपये तक का संपार्श्विक-मुक्त ऋण प्रदान करता है।',
    benefitsEn: 'No collateral required, affordable interest rates (8.5% - 11%), MUDRA Debit Card for working capital.',
    benefitsMr: 'विनातारण कर्ज, वाजवी व्याजदर आणि खेळत्या भांडवलासाठी मुद्रा डेबिट कार्ड.',
    benefitsHi: 'बिना किसी गारंटी के ऋण और रियायती ब्याज दरें।',
    benefitType: 'Loan',
    department: 'Department of Financial Services, Ministry of Finance',
    level: 'CENTRAL',
    state: 'All India',
    categoryId: 'cat-4',
    category: FALLBACK_CATEGORIES[3],
    applicationMode: 'BOTH',
    applicationUrl: 'https://www.udyamimitra.in',
    portalName: 'Udyami Mitra / JanSamarth Portal',
    applicationDeadline: 'Rolling / Always Open',
    isFeatured: true,
    isPublished: true,
    viewsCount: 1980,
    savesCount: 420,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    applicationStepsEn: JSON.stringify([
      'Prepare Business Plan and quotation for machinery/items.',
      'Apply online on udyamimitra.in or visit your local bank branch.',
      'Bank branch sanctions the loan without third-party collateral.',
    ]),
    applicationStepsMr: JSON.stringify([
      'व्यवसायाचा आराखडा (Project Report) तयार करा.',
      'udyamimitra.in वर ऑनलाइन अर्ज करा किंवा नजीकच्या बँकेत जा.',
      'बँक पडताळणीनंतर विनातारण कर्ज मंजूर करते.',
    ]),
    applicationStepsHi: JSON.stringify([
      'जनसमर्थ पोर्टल या नजदीकी बैंक शाखा में आवेदन करें।',
    ]),
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 65,
      allowedGenders: 'Any',
      allowedStates: 'All India',
      allowedOccupations: JSON.stringify(['Business Owner', 'Unemployed', 'Daily Wage', 'Other']),
      allowedEducation: 'Any',
      maxAnnualIncome: null,
      allowedCategories: 'Any',
      requiresDisability: false,
      requiresBpl: false,
    },
    requiredDocuments: [
      {
        id: 'doc-401',
        schemeId: 'sch-4',
        nameEn: 'Aadhaar & PAN Card',
        nameMr: 'आधार कार्ड व पॅन कार्ड',
        nameHi: 'आधार और पैन कार्ड',
        descriptionEn: 'Government photo identity proof.',
        isMandatory: true,
        issuanceAuthority: 'Govt of India',
        documentType: 'Identity',
      },
      {
        id: 'doc-402',
        schemeId: 'sch-4',
        nameEn: 'Quotation / Proforma Invoice of Machinery',
        nameMr: 'खरेदी करावयाच्या यंत्रसामग्रीचे कोटेशन',
        nameHi: 'उपकरणों/सामग्रियों का कोटेशन',
        descriptionEn: 'Vendor quotation for capital expenditure.',
        isMandatory: true,
        issuanceAuthority: 'Authorized Vendor',
        documentType: 'Other',
      },
    ],
  },
  {
    id: 'sch-5',
    slug: 'pm-vishwakarma-scheme',
    titleEn: 'PM Vishwakarma Kaushal Samman Yojana',
    titleMr: 'प्रधानमंत्री विश्वकर्मा कौशल्य सन्मान योजना',
    titleHi: 'प्रधानमंत्री विश्वकर्मा योजना',
    shortSummaryEn: '₹15,000 toolkit grant, 5-7 days paid skill training (₹500/day), and collateral-free credit up to ₹3,00,000 at 5% interest for traditional artisans.',
    shortSummaryMr: 'पारंपरिक १८ कारागिरांसाठी ₹१५,००० मोफत टूलकिट अनुदान, दररोज ₹५०० मानधनासह प्रशिक्षण आणि ५% व्याजाने ₹३ लाखांपर्यंत कर्ज.',
    shortSummaryHi: 'पारंपरिक 18 ट्रेड के कारीगरों के लिए ₹15,000 टूलकिट अनुदान, ₹500/दिन वजीफे के साथ कौशल प्रशिक्षण और ₹3 लाख तक का ऋण।',
    detailedDescriptionEn: 'PM Vishwakarma supports traditional artisans (carpenter, blacksmith, potter, cobbler, tailor, mason, etc.) with skill training and credit linkages.',
    detailedDescriptionMr: 'सुतार, लोहार, कुंभार, सोनार, चर्मकार, शिंपी अशा १८ पारंपरिक व्यवसायातील कारागिरांना आर्थिक बळ देण्यासाठी ही योजना आहे.',
    detailedDescriptionHi: 'पारंपरिक कारीगरों को टूलकिट, आधुनिक प्रशिक्षण और न्यूनतम ब्याज पर वित्तीय सहायता दी जाती है।',
    benefitsEn: 'PM Vishwakarma ID Card + ₹15,000 toolkit voucher + ₹500/day training stipend + ₹3 Lakh enterprise loan at 5% interest.',
    benefitsMr: 'अधिकृत प्रमाणपत्र + दररोज ₹५०० मानधनासह प्रशिक्षण + ₹१५,००० टूलकिट व्हाऊचर + ५% व्याजाने ₹३ लाखांपर्यंत कर्ज.',
    benefitsHi: 'विश्वकर्मा प्रमाण पत्र + ₹500/दिन वजीफा + ₹15,000 टूलकिट वाउचर + ₹3 लाख तक का ऋण।',
    benefitType: 'Training & Subsidy',
    department: 'Ministry of MSME, Govt of India',
    level: 'CENTRAL',
    state: 'All India',
    categoryId: 'cat-7',
    category: FALLBACK_CATEGORIES[6],
    applicationMode: 'BOTH',
    applicationUrl: 'https://pmvishwakarma.gov.in',
    portalName: 'PM Vishwakarma Portal (pmvishwakarma.gov.in)',
    applicationDeadline: 'Rolling / Always Open',
    isFeatured: true,
    isPublished: true,
    viewsCount: 1650,
    savesCount: 310,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    applicationStepsEn: JSON.stringify([
      'Visit nearest CSC (Common Service Centre) with Aadhaar and bank passbook.',
      'Complete biometric verification and select your trade from the 18 eligible trades.',
      'Attend 5-day basic training and receive ₹15,000 toolkit digital voucher.',
    ]),
    applicationStepsMr: JSON.stringify([
      'नजीकच्या सीएससी (CSC) केंद्रावर जाऊन बायोमेट्रिक नोंदणी करा.',
      '५ दिवसांचे प्रशिक्षण पूर्ण करून ₹१५,००० चे टूलकिट व्हाऊचर मिळवा.',
    ]),
    applicationStepsHi: JSON.stringify([
      'निकटतम सीएससी (CSC) केंद्र पर जाएं और आधार बायोमेट्रिक सत्यापन कराएं।',
    ]),
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 70,
      allowedGenders: 'Any',
      allowedStates: 'All India',
      allowedOccupations: JSON.stringify(['Daily Wage', 'Business Owner', 'Unemployed', 'Other']),
      allowedEducation: 'Any',
      maxAnnualIncome: null,
      allowedCategories: 'Any',
      requiresDisability: false,
      requiresBpl: false,
    },
    requiredDocuments: [
      {
        id: 'doc-501',
        schemeId: 'sch-5',
        nameEn: 'Aadhaar Card',
        nameMr: 'आधार कार्ड',
        nameHi: 'आधार कार्ड',
        descriptionEn: 'Aadhaar with mobile linkage.',
        isMandatory: true,
        issuanceAuthority: 'UIDAI',
        documentType: 'Identity',
      },
    ],
  },
  {
    id: 'sch-6',
    slug: 'sukanya-samriddhi-yojana-ssy',
    titleEn: 'Sukanya Samriddhi Yojana (SSY)',
    titleMr: 'सुकन्या समृद्धी योजना (मुलींच्या उज्ज्वल भविष्यासाठी)',
    titleHi: 'सुकन्या समृद्धि योजना (एसएसवाई)',
    shortSummaryEn: 'High-interest government savings scheme (8.2% p.a.) with 100% tax exemption under Section 80C for girl child education and marriage.',
    shortSummaryMr: 'मुलींच्या उच्च शिक्षण व विवाहासाठी केंद्र शासनाची सर्वोच्च व्याजदर देणारी (८.२% वार्षिक) व करमुक्त बचत योजना.',
    shortSummaryHi: 'बेटियों की उच्च शिक्षा और विवाह के लिए सरकार समर्थित 8.2% ब्याज दर वाली बचत योजना।',
    detailedDescriptionEn: 'Sukanya Samriddhi Account encourages parents to build a fund for the future education and marriage expenses of female children.',
    detailedDescriptionMr: '१० वर्षांखालील मुलींच्या नावाने पोस्ट ऑफिस किंवा बँकेत हे खाते उघडून वार्षिक ८.२% चक्रवाढ व्याज व कर सवलत मिळते.',
    detailedDescriptionHi: '10 वर्ष से कम आयु की बालिकाओं के लिए खोला जा सकता है। 8.2% की आकर्षक ब्याज दर और पूर्ण आयकर छूट।',
    benefitsEn: '8.2% compounded annual interest rate + Complete Triple Tax Exemption (EEE) under Section 80C.',
    benefitsMr: '८.२% चक्रवाढ वार्षिक व्याजदर + कलम ८०सी अंतर्गत संपूर्ण कर सवलत.',
    benefitsHi: '8.2% चक्रवृद्धि ब्याज दर + धारा 80सी के तहत पूर्ण कर छूट।',
    benefitType: 'Subsidy & Savings',
    department: 'Ministry of Finance, Govt of India',
    level: 'CENTRAL',
    state: 'All India',
    categoryId: 'cat-5',
    category: FALLBACK_CATEGORIES[4],
    applicationMode: 'BOTH',
    applicationUrl: 'https://www.indiapost.gov.in',
    portalName: 'India Post / Authorized Commercial Banks',
    applicationDeadline: 'Rolling / Open until girl turns 10',
    isFeatured: false,
    isPublished: true,
    viewsCount: 1820,
    savesCount: 290,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    applicationStepsEn: JSON.stringify([
      'Collect SSY Account Opening Form from any India Post Office branch or bank.',
      'Attach girl child Birth Certificate and guardian Aadhaar/PAN cards.',
      'Deposit initial amount (minimum ₹250) and collect passbook.',
    ]),
    applicationStepsMr: JSON.stringify([
      'पोस्ट ऑफिस किंवा बँकेतून सुकन्या समृद्धी अर्ज घ्या.',
      'मुलीचा जन्म दाखला आणि पालकांचे आधार कार्ड जोडून खाते सुरू करा.',
    ]),
    applicationStepsHi: JSON.stringify([
      'डाकघर या अधिकृत बैंक से सुकन्या समृद्धि खाता खोलने का फॉर्म जमा करें।',
    ]),
    eligibilityCriteria: {
      minAge: 0,
      maxAge: 10,
      allowedGenders: JSON.stringify(['Female']),
      allowedStates: 'All India',
      allowedOccupations: 'Any',
      allowedEducation: 'Any',
      maxAnnualIncome: null,
      allowedCategories: 'Any',
      requiresDisability: false,
      requiresBpl: false,
    },
    requiredDocuments: [
      {
        id: 'doc-601',
        schemeId: 'sch-6',
        nameEn: 'Girl Child Birth Certificate',
        nameMr: 'मुलीचा जन्म दाखला',
        nameHi: 'बालिका का जन्म प्रमाण पत्र',
        descriptionEn: 'Official birth certificate issued by municipal registrar.',
        isMandatory: true,
        issuanceAuthority: 'Registrar of Births & Deaths',
        documentType: 'Identity',
      },
    ],
  },
  {
    id: 'sch-7',
    slug: 'pradhan-mantri-awas-yojana-urban-gramin',
    titleEn: 'Pradhan Mantri Awas Yojana (PMAY Housing For All)',
    titleMr: 'प्रधानमंत्री आवास योजना (सर्वांसाठी पक्की घरे)',
    titleHi: 'प्रधानमंत्री आवास योजना (पीएमएवाई)',
    shortSummaryEn: 'Financial grant of ₹1.2 Lakh to ₹2.67 Lakhs subsidy for building or purchasing a pucca house with basic amenities.',
    shortSummaryMr: 'आर्थिक दुर्बल आणि बेघर नागरिकांना स्वतःचे हक्काचे पक्के घर बांधण्यासाठी ₹१.२० लाख ते ₹२.६७ लाखांपर्यंत थेट अनुदान.',
    shortSummaryHi: 'कच्चे मकानों में रहने वाले परिवारों को पक्का मकान बनाने के लिए ₹1.20 लाख से ₹2.67 लाख तक की वित्तीय सहायता।',
    detailedDescriptionEn: 'PMAY provides affordable housing assistance to eligible families in urban and rural areas across India.',
    detailedDescriptionMr: 'ग्रामीण भागातील बेघर कुटुंबांना ₹१.२० लाखांचे थेट बांधकाम अनुदान दिले जाते. शहरी भागात गृहकर्जावर व्याज अनुदान मिळते.',
    detailedDescriptionHi: 'पात्र लाभार्थियों को पक्के मकान के निर्माण अथवा खरीद हेतु सीधी आर्थिक सहायता प्रदान की जाती है।',
    benefitsEn: 'PMAY-Gramin: Direct DBT grant of ₹1,20,000 + 90 days MGNREGA wages + ₹12,000 for toilet.',
    benefitsMr: 'ग्रामीण भागासाठी ₹१,२०,००० थेट बांधकाम अनुदान + ९० दिवसांचे मनरेगा मजुरी मानधन + ₹१२,००० शौचालय अनुदान.',
    benefitsHi: 'ग्रामीण क्षेत्रों में ₹1,20,000 प्रत्यक्ष अनुदान + मनरेगा मजदूरी।',
    benefitType: 'Subsidy & Grant',
    department: 'Ministry of Housing and Urban Affairs / Rural Development',
    level: 'CENTRAL',
    state: 'All India',
    categoryId: 'cat-6',
    category: FALLBACK_CATEGORIES[5],
    applicationMode: 'BOTH',
    applicationUrl: 'https://pmaymis.gov.in',
    portalName: 'PMAY-MIS / AwaasApp',
    applicationDeadline: 'Rolling / Phase Wise',
    isFeatured: false,
    isPublished: true,
    viewsCount: 2890,
    savesCount: 450,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    applicationStepsEn: JSON.stringify([
      'Contact Gram Sevak or Village Panchayat to verify entry in Awaas+ list.',
      'Geotagging of existing kuccha house is completed via AwaasApp.',
      'Installment funds released directly into bank account at foundation and roof levels.',
    ]),
    applicationStepsMr: JSON.stringify([
      'ग्रामपंचायत किंवा ग्रामसेवकाशी संपर्क साधून आवास+ यादीतील नाव तपासा.',
      'घराचे जिओ-टॅगिंग झाल्यानंतर किस्तोंमध्ये अनुदान खात्यात जमा होते.',
    ]),
    applicationStepsHi: JSON.stringify([
      'ग्राम पंचायत में आवास सूची में अपना नाम सत्यापित करें।',
    ]),
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 75,
      allowedGenders: 'Any',
      allowedStates: 'All India',
      allowedOccupations: 'Any',
      allowedEducation: 'Any',
      maxAnnualIncome: 300000,
      allowedCategories: 'Any',
      requiresDisability: false,
      requiresBpl: true,
    },
    requiredDocuments: [
      {
        id: 'doc-701',
        schemeId: 'sch-7',
        nameEn: 'Aadhaar Card of all family members',
        nameMr: 'कुटुंबातील सर्व सदस्यांचे आधार कार्ड',
        nameHi: 'परिवार के सभी सदस्यों का आधार कार्ड',
        descriptionEn: 'Aadhaar copies for biometric linkage.',
        isMandatory: true,
        issuanceAuthority: 'UIDAI',
        documentType: 'Identity',
      },
    ],
  },
  {
    id: 'sch-8',
    slug: 'national-apprenticeship-promotion-scheme-naps',
    titleEn: 'National Apprenticeship Promotion Scheme (NAPS)',
    titleMr: 'राष्ट्रीय शिकाऊ उमेदवारी प्रोत्साहन योजना (NAPS)',
    titleHi: 'राष्ट्रीय शिक्षुता प्रोत्साहन योजना (एनएपीएस)',
    shortSummaryEn: 'Government pays 25% of monthly stipend (up to ₹1,500/month) directly to ITI, Diploma, and Graduate apprentices in industry.',
    shortSummaryMr: 'औद्योगिक प्रशिक्षण घेणाऱ्या आयटीआय, पदविका व पदवीधर शिकाऊ उमेदवारांना दरमहा शासनाकडून थेट २५% (₹१,५०० पर्यंत) विद्यावेतन.',
    shortSummaryHi: 'उद्योगों में प्रशिक्षण ले रहे आईटीआई, डिप्लोमा और स्नातक प्रशिक्षुओं को सरकार द्वारा ₹1,500 प्रति माह तक का प्रत्यक्ष वजीफा।',
    detailedDescriptionEn: 'NAPS promotes apprenticeship training in industry by providing direct stipend subsidies to youth.',
    detailedDescriptionMr: 'युवकांना कारखान्यांमध्ये प्रत्यक्ष कामाचा अनुभव मिळवून देण्यासाठी मासिक विद्यावेतन दिले जाते.',
    detailedDescriptionHi: 'युवाओं को उद्योगों में हैंड्स-ऑन ट्रेनिंग और अनुभव प्रदान करने के लिए राष्ट्रीय योजना।',
    benefitsEn: 'Monthly stipend of ₹7,000 to ₹15,000 + National Apprenticeship Certificate (NAC).',
    benefitsMr: 'दरमहा ₹७,००० ते ₹१५,००० विद्यावेतन + राष्ट्रीय शिकाऊ उमेदवारी प्रमाणपत्र (NAC).',
    benefitsHi: 'मासिक वजीफा + राष्ट्रीय शिक्षुता प्रमाण पत्र।',
    benefitType: 'Training & Stipend',
    department: 'Ministry of Skill Development and Entrepreneurship',
    level: 'CENTRAL',
    state: 'All India',
    categoryId: 'cat-7',
    category: FALLBACK_CATEGORIES[6],
    applicationMode: 'ONLINE',
    applicationUrl: 'https://www.apprenticeshipindia.gov.in',
    portalName: 'Apprenticeship India Portal',
    applicationDeadline: 'Rolling / Year Round',
    isFeatured: false,
    isPublished: true,
    viewsCount: 1340,
    savesCount: 260,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    applicationStepsEn: JSON.stringify([
      'Register on apprenticeshipindia.gov.in using Aadhaar.',
      'Search for apprenticeship opportunities and click Apply.',
      'Receive monthly stipend via DBT directly into bank account.',
    ]),
    applicationStepsMr: JSON.stringify([
      'apprenticeshipindia.gov.in वर उमेदवार म्हणून नोंदणी करा.',
      'आवडीच्या कंपनीत अर्ज करा व दरमहा विद्यावेतन मिळवा.',
    ]),
    applicationStepsHi: JSON.stringify([
      'apprenticeshipindia.gov.in पर पंजीकरण करें और आवेदन करें।',
    ]),
    eligibilityCriteria: {
      minAge: 14,
      maxAge: 35,
      allowedGenders: 'Any',
      allowedStates: 'All India',
      allowedOccupations: JSON.stringify(['Student', 'Unemployed']),
      allowedEducation: JSON.stringify(['10th Pass', '12th Pass', 'Diploma', 'Undergraduate']),
      maxAnnualIncome: null,
      allowedCategories: 'Any',
      requiresDisability: false,
      requiresBpl: false,
    },
    requiredDocuments: [
      {
        id: 'doc-801',
        schemeId: 'sch-8',
        nameEn: 'Educational Certificates (10th/ITI/Diploma/Degree)',
        nameMr: 'शैक्षणिक प्रमाणपत्रे व गुणपत्रिका',
        nameHi: 'शैक्षणिक अंकतालिका और प्रमाण पत्र',
        descriptionEn: 'Proof of qualifying examination.',
        isMandatory: true,
        issuanceAuthority: 'Board / University / NCVT',
        documentType: 'Education',
      },
    ],
  },
  {
    id: 'sch-9',
    slug: 'sanjay-gandhi-niradhar-anudan-yojana',
    titleEn: 'Sanjay Gandhi Niradhar Anudan Yojana',
    titleMr: 'संजय गांधी निराधार अनुदान योजना (महाराष्ट्र शासन)',
    titleHi: 'संजय गांधी निराधार अनुदान योजना',
    shortSummaryEn: 'Monthly financial pension of ₹1,500 per month provided by Maharashtra Government to destitute persons, widows, and persons with severe disabilities.',
    shortSummaryMr: 'निराधार व्यक्ती, विधवा महिला आणि गंभीर दिव्यांग व्यक्तींना दरमहा ₹१,५०० ची थेट पेन्शन मदत.',
    shortSummaryHi: 'निराश्रित व्यक्तियों, विधवाओं और दिव्यांगजनों को महाराष्ट्र सरकार द्वारा ₹1,500 प्रति माह की पेंशन।',
    detailedDescriptionEn: 'Provides social security pension to destitute persons below poverty line, elderly above 65, widows, and persons with disabilities in Maharashtra.',
    detailedDescriptionMr: 'समाजातील दुर्बल, निराधार, विधवा व दिव्यांगांना सन्मानाने जगता यावे म्हणून दरमहा ₹१,५०० थेट बँक खात्यात दिले जातात.',
    detailedDescriptionHi: 'महाराष्ट्र सरकार द्वारा समाज के निराश्रित, बुजुर्ग और विधवाओं को ₹1,500 प्रति माह पेंशन।',
    benefitsEn: '₹1,500 monthly pension transferred directly via DBT to beneficiary bank account.',
    benefitsMr: 'दरमहा ₹१,५०० थेट बँक खात्यात कायमस्वरूपी पेन्शन स्वरूपात जमा.',
    benefitsHi: '₹1,500 प्रति माह सीधे बैंक खाते में पेंशन के रूप में।',
    benefitType: 'Direct Benefit Transfer',
    department: 'Social Justice & Special Assistance Department, Govt of Maharashtra',
    level: 'STATE',
    state: 'Maharashtra',
    categoryId: 'cat-8',
    category: FALLBACK_CATEGORIES[7],
    applicationMode: 'BOTH',
    applicationUrl: 'https://sjsa.maharashtra.gov.in',
    portalName: 'Aaple Sarkar / Tahsildar Sanjay Gandhi Desk',
    applicationDeadline: 'Rolling / Always Open',
    isFeatured: false,
    isPublished: true,
    viewsCount: 2150,
    savesCount: 390,
    lastVerifiedAt: '2026-08-20T00:00:00Z',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
    applicationStepsEn: JSON.stringify([
      'Obtain application form from Tahsildar office or Aaple Sarkar portal.',
      'Attach Age Proof, Tehsildar Income Certificate (below ₹50,000), and 15-year Maharashtra Domicile.',
      'Submit at Tahsildar Sanjay Gandhi Desk to receive monthly pension.',
    ]),
    applicationStepsMr: JSON.stringify([
      'तहसील कार्यालयातून किंवा आपले सरकार पोर्टलवरून अर्ज घ्या.',
      '₹५०,००० पेक्षा कमी उत्पन्नाचा दाखला आणि १५ वर्षे अधिवास पुरावा जोडा.',
      'मंजुरीनंतर दरमहा ₹१,५०० बँक खात्यात सुरू होतात.',
    ]),
    applicationStepsHi: JSON.stringify([
      'तहसील कार्यालय से आवेदन पत्र प्राप्त करके जमा करें।',
    ]),
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 100,
      allowedGenders: 'Any',
      allowedStates: 'Maharashtra',
      allowedOccupations: JSON.stringify(['Unemployed', 'Daily Wage', 'Other']),
      allowedEducation: 'Any',
      maxAnnualIncome: 50000,
      allowedCategories: 'Any',
      requiresDisability: false,
      requiresBpl: true,
    },
    requiredDocuments: [
      {
        id: 'doc-901',
        schemeId: 'sch-9',
        nameEn: 'Tehsildar Income Certificate (Below ₹50,000)',
        nameMr: 'तहसीलदार कार्यालयाचा उत्पन्नाचा दाखला (वार्षिक ₹५०,००० आत)',
        nameHi: 'आय प्रमाण पत्र (₹50,000 से कम)',
        descriptionEn: 'Valid annual income certificate.',
        isMandatory: true,
        issuanceAuthority: 'Tehsildar',
        documentType: 'Income',
      },
    ],
  },
];
